import logging
import fclpy.lisptype as lisptype
import fclpy.lispenv as lispenv
import fclpy.state as state


EXPECTED_LISP_FUNCTIONS = [
    'CAR','CDR','CONS','LIST','APPEND','REVERSE','LENGTH','LAST','FIRST','SECOND','THIRD','FOURTH','FIFTH','REST',
    'CADR','CADDR','CADDDR','CDDR','CDDDR','CAAR','CAAAR','CAAAAR','CAAADR','CAADAR','CAADDR','CAADR','CADAAR','CADADR','CADAR','CADDAR',
    'CDAR','CDAAR','CDAAAR','CDAADR','CDADAR','CDADDR','CDADR','CDDAAR','CDDADR','CDDAR','CDDDAR','CDDDDR',
    'ATOM','CONSP','LISTP','NULL','SYMBOLP','STRINGP','NUMBERP','INTEGERP','FLOATP','FUNCTIONP','COMPILED-FUNCTION-P','ARRAYP','HASH-TABLE-P','KEYWORDP','ZEROP','ALPHA-CHAR-P','ALPHANUMERICP','GRAPHIC-CHAR-P','INPUT-STREAM-P','INTERACTIVE-STREAM-P','ADJUSTABLE-ARRAY-P','ARRAY-HAS-FILL-POINTER-P','FBOUNDP',
    'EQ','EQUAL',
    '+','-','*','/','=','<','>','<=','>=','/=','1+','1-',
    'FLOOR','CEILING','ROUND','TRUNCATE','EXP','EXPT','GCD','LCM','MAX','MIN','PLUSP','MINUSP','EVENP','ODDP','MOD','ISQRT',
    'COS','ACOS','ACOSH','ASIN','ASINH','ATAN','ATANH',
    'FLOAT','DECODE-FLOAT','INTEGER-DECODE-FLOAT','SCALE-FLOAT','FLOAT-DIGITS','FLOAT-PRECISION','FLOAT-RADIX','FLOAT-SIGN',
    'FIND','FIND-IF','FIND-IF-NOT','MEMBER','MEMBER-IF','MEMBER-IF-NOT','INTERSECTION','MERGE','MISMATCH','FILL','BUTLAST',
    'ARRAY-DIMENSION','ADJUST-ARRAY',
    'HASH-TABLE-COUNT','HASH-TABLE-SIZE','HASH-TABLE-TEST','HASH-TABLE-REHASH-SIZE','HASH-TABLE-REHASH-THRESHOLD',
    'MERGE-PATHNAMES','HOST-NAMESTRING','FILE-NAMESTRING',
    'GET','RPLACA','RPLACD',
    'INTERN','FIND-SYMBOL','FIND-PACKAGE','FIND-ALL-SYMBOLS','EXPORT','IMPORT','IN-PACKAGE','GENTEMP','APROPOS','APROPOS-LIST',
    'FDEFINITION','FMAKUNBOUND','FUNCTION-KEYWORDS','FUNCTION-LAMBDA-EXPRESSION',
    'COMPILE-FILE-PATHNAME','DELETE-FILE','FILE-AUTHOR','FILE-STRING-LENGTH','FILE-WRITE-DATE','PROBE-FILE','RENAME-FILE',
    'GET-OUTPUT-STREAM-STRING','STREAM-EXTERNAL-FORMAT',
    'FORMAT','FORMATTER','SIMPLE-CONDITION-FORMAT-ARGUMENTS','SIMPLE-CONDITION-FORMAT-CONTROL',
    'GET-DECODED-TIME','GET-INTERNAL-REAL-TIME','GET-INTERNAL-RUN-TIME','INTERNAL-TIME-UNITS-PER-SECOND',
    'GET-MACRO-CHARACTER','SET-DISPATCH-MACRO-CHARACTER','GET-DISPATCH-MACRO-CHARACTER',
    'FIND-CLASS','FIND-METHOD','ADD-METHOD','ALLOCATE-INSTANCE','INITIALIZE-INSTANCE','UPDATE-INSTANCE-FOR-DIFFERENT-CLASS','UPDATE-INSTANCE-FOR-REDEFINED-CLASS','SLOT-MISSING','INVALID-METHOD-ERROR',
    'INVOKE-DEBUGGER','INVOKE-RESTART','INVOKE-RESTART-INTERACTIVELY','ABORT',
    'MOST-POSITIVE-FIXNUM','MOST-NEGATIVE-FIXNUM','MOST-NEGATIVE-LONG-FLOAT','MOST-NEGATIVE-SHORT-FLOAT','LAMBDA-LIST-KEYWORDS','LAMBDA-PARAMETERS-LIMIT',
    'IDENTITY','COPY-TREE','INSPECT','INCF','MAKE-LOAD-FORM','MAKE-LOAD-FORM-SAVING-SLOTS','PPRINT-FILL','LIST*',
    'KEYWORD','INTEGER','FIXNUM','DOUBLE-FLOAT','SINGLE-FLOAT','SHORT-FLOAT','EXTENDED-CHAR','HASH-TABLE','GENERIC-FUNCTION','FILE-STREAM','FILE-ERROR','END-OF-FILE','FLOATING-POINT-INEXACT','FLOATING-POINT-INVALID-OPERATION','FLOATING-POINT-OVERFLOW','FLOATING-POINT-UNDERFLOW','ARITHMETIC-ERROR-OPERANDS','ARITHMETIC-ERROR-OPERATION','FILE-ERROR-PATHNAME',
    'PRINT','READ','ERROR','GENSYM','EVAL','APPLY',
    'IF','COND','DEFUN','SETQ','DEFVAR','LET','WHEN','FLET','LABELS','HANDLER-BIND','HANDLER-CASE','WITH-OPEN-FILE','LOOP-FINISH','INLINE','IGNORE','IGNORABLE',
    'ABS','REM','NUMERATOR','DENOMINATOR','SQRT','LOG','SIN','TAN','SINH','COSH','TANH','CONJUGATE','LOGAND','LOGIOR','LOGXOR','LOGNOT','LOGTEST','LOGBITP','LOGCOUNT',
    'ENDP','NTH','NTHCDR','NREVERSE','SIXTH','SEVENTH','EIGHTH','NINTH','TENTH','NBUTLAST','ELT','SUBSEQ','COPY-SEQ','COUNT','COUNT-IF','COUNT-IF-NOT','POSITION','POSITION-IF','POSITION-IF-NOT','REMOVE','REMOVE-IF','REMOVE-IF-NOT','SUBSTITUTE','SUBSTITUTE-IF','SUBSTITUTE-IF-NOT',
    'CHAR','CHAR-CODE','CODE-CHAR','CHARACTER','CHAR-UPCASE','CHAR-DOWNCASE','UPPER-CASE-P','LOWER-CASE-P','DIGIT-CHAR-P','STANDARD-CHAR-P',
    'STRING','STRING-UPCASE','STRING-DOWNCASE','STRING-CAPITALIZE','UNLESS','PROG1','PROG2','VECTOR','VECTORP','UNION','NUNION','SET-DIFFERENCE','NSET-DIFFERENCE','SET-EXCLUSIVE-OR','NSET-EXCLUSIVE-OR','SUBSETP','COPY-ALIST','TREE-EQUAL','SUBST','SUBST-IF','SUBST-IF-NOT','SUBLIS','TYPEP',
    'TYPE-OF','SUBTYPEP','RATIONALP','REALP','COMPLEXP','CHARACTERP','PACKAGEP','PATHNAMEP','READTABLEP','STREAMP','PRINC','PRIN1','TERPRI','SET','BOUNDP','MAKUNBOUND','FUNCALL','CONSTANTLY','COMPLEMENT','VALUES','VALUES-LIST','RANDOM','MAKE-RANDOM-STATE','BLOCK','RETURN-FROM','CATCH','THROW','TAGBODY','GO','UNWIND-PROTECT',
    'AND','OR','PROG','PROGN','WHEN','UNLESS','CASE','COND',
    'MAKE-ARRAY','ARRAY-DIMENSIONS','ARRAY-ELEMENT-TYPE','ARRAY-RANK','ARRAY-TOTAL-SIZE','ARRAY-IN-BOUNDS-P','ARRAY-DISPLACEMENT',
    'MAKE-SEQUENCE','CONCATENATE','MAP','REDUCE','SORT','STABLE-SORT','SEARCH','REPLACE','BIT','SBIT','BIT-AND','BIT-IOR','BIT-XOR','BIT-EQV','BIT-NAND','BIT-NOR','BIT-ANDC1','BIT-ANDC2','BIT-ORC1','BIT-ORC2','BIT-NOT','BIT-VECTOR-P','SIMPLE-BIT-VECTOR-P',
    'CHAR=','CHAR/=','CHAR<','CHAR>','CHAR<=','CHAR>=','CHAR-EQUAL','CHAR-NOT-EQUAL','CHAR-LESSP','CHAR-GREATERP','CHAR-NOT-GREATERP','CHAR-NOT-LESSP','BOTH-CASE-P','CHAR-INT','INT-CHAR','CHAR-NAME','NAME-CHAR','DIGIT-CHAR',
    'SCHAR','STRING=','STRING/=','STRING<','STRING>','STRING<=','STRING>=','STRING-EQUAL','STRING-NOT-EQUAL','STRING-LESSP','STRING-GREATERP','STRING-NOT-GREATERP','STRING-NOT-LESSP','NSTRING-UPCASE','NSTRING-DOWNCASE','NSTRING-CAPITALIZE','STRING-TRIM','STRING-LEFT-TRIM','STRING-RIGHT-TRIM','PARSE-INTEGER',
    'MAKE-HASH-TABLE','GETHASH','REMHASH','MAPHASH','CLRHASH','SXHASH','GETF','GET-PROPERTIES','PUTPROP','REMPROP','SYMBOL-PLIST','REMF',
    'NCONC','REVAPPEND','NRECONC','PUSH','POP','PUSHNEW','NSUBSTITUTE','NSUBSTITUTE-IF','NSUBSTITUTE-IF-NOT','DELETE','DELETE-IF','DELETE-IF-NOT','DELETE-DUPLICATES','REMOVE-DUPLICATES','NINTERSECTION','NSUBST','NSUBST-IF','NSUBST-IF-NOT','NSUBLIS',
    'READ-LINE','READ-CHAR','READ-BYTE','WRITE-CHAR','WRITE-STRING','WRITE-LINE','WRITE-BYTE','PEEK-CHAR','UNREAD-CHAR','LISTEN','CLEAR-INPUT','CLEAR-OUTPUT','WRITE','PRIN1-TO-STRING','PRINC-TO-STRING','WRITE-TO-STRING',
    'PATHNAME','PATHNAME-HOST','PATHNAME-DEVICE','PATHNAME-DIRECTORY','PATHNAME-NAME','PATHNAME-TYPE','PATHNAME-VERSION','MAKE-PATHNAME','NAMESTRING','DIRECTORY-NAMESTRING','ENOUGH-NAMESTRING','PARSE-NAMESTRING','WILD-PATHNAME-P','PATHNAME-MATCH-P','TRANSLATE-PATHNAME','LOGICAL-PATHNAME','TRANSLATE-LOGICAL-PATHNAME','TRUENAME',
    'OPEN','CLOSE','OUTPUT-STREAM-P','OPEN-STREAM-P','STREAM-ELEMENT-TYPE','MAKE-STRING-INPUT-STREAM','MAKE-STRING-OUTPUT-STREAM','MAKE-BROADCAST-STREAM','MAKE-CONCATENATED-STREAM','MAKE-ECHO-STREAM','MAKE-SYNONYM-STREAM','MAKE-TWO-WAY-STREAM',
    'GET-UNIVERSAL-TIME','DECODE-UNIVERSAL-TIME','ENCODE-UNIVERSAL-TIME','SLEEP','MULTIPLE-VALUE-BIND','MULTIPLE-VALUE-CALL','MULTIPLE-VALUE-LIST','MULTIPLE-VALUE-PROG1','MULTIPLE-VALUE-SETQ','NTH-VALUE',
    'SYMBOL-NAME','SYMBOL-PACKAGE','SYMBOL-VALUE','SYMBOL-FUNCTION','MAKE-SYMBOL','COPY-SYMBOL','MAKE-PACKAGE','PACKAGE-NAME','PACKAGE-NICKNAMES','RENAME-PACKAGE','PACKAGE-USE-LIST','PACKAGE-USED-BY-LIST','PACKAGE-SHADOWING-SYMBOLS','LIST-ALL-PACKAGES','UNINTERN','UNEXPORT','SHADOWING-IMPORT','SHADOW','USE-PACKAGE','UNUSE-PACKAGE',
    'MACROEXPAND','MACROEXPAND-1','ARRAY-DIMENSION-LIMIT','ARRAY-RANK-LIMIT','ARRAY-TOTAL-SIZE-LIMIT','CALL-ARGUMENTS-LIMIT','MULTIPLE-VALUES-LIMIT','CHAR-CODE-LIMIT','CONSTANTP','SPECIAL-OPERATOR-P','MACRO-FUNCTION',
    'DO','DOLIST','DOTIMES','LOOP','EVAL-WHEN','LOAD','EQUALP','NOT','EQL','EQUAL','DO-SYMBOLS','DO-EXTERNAL-SYMBOLS','DO-ALL-SYMBOLS','DOCUMENTATION','PI','LEAST-POSITIVE-DOUBLE-FLOAT','LEAST-NEGATIVE-DOUBLE-FLOAT','DOUBLE-FLOAT-EPSILON','DOUBLE-FLOAT-NEGATIVE-EPSILON','MOST-POSITIVE-DOUBLE-FLOAT','MOST-NEGATIVE-DOUBLE-FLOAT','EVERY','SOME','NOTEVERY','NOTANY','MAPCAR','MAPC','MAPCAN','MAPL','MAPLIST','APPLY',
    'FILE-POSITION','FILE-LENGTH','FRESH-LINE','FINISH-OUTPUT','FORCE-OUTPUT','STRING','CHAR','AREF','SVREF','VECTOR','SIMPLE-VECTOR-P','VECTOR-POP','VECTOR-PUSH','VECTOR-PUSH-EXTEND','FILL-POINTER','SIMPLE-STRING-P','RANDOM-STATE-P','SIGNUM','CIS','CONJUGATE','PHASE','REALPART','IMAGPART','ASH','LDB','DPB','LDB-TEST','BYTE','BYTE-SIZE','BYTE-POSITION','MASK-FIELD','DEPOSIT-FIELD','INTEGER-LENGTH','ASSOC','ASSOC-IF','ASSOC-IF-NOT','RASSOC','RASSOC-IF','RASSOC-IF-NOT','PAIRLIS','TYPECASE','ETYPECASE','CTYPECASE','COMPILE','COMPILE-FILE','EVAL','COPY-PPRINT-DISPATCH','PPRINT','PPRINT-DISPATCH','PPRINT-EXIT-IF-LIST-EXHAUSTED','PPRINT-INDENT','PPRINT-LINEAR','PPRINT-LOGICAL-BLOCK','PPRINT-NEWLINE','PPRINT-POP','PPRINT-TAB','DECF','PSETF','SETF','SHIFTF','ROTATEF','PACKAGE-ERROR-PACKAGE','WITH-PACKAGE-ITERATOR','EXPORT','IMPORT',
    'ARRAY-ROW-MAJOR-INDEX','BREAK','CCASE','CHAR-BITS-LIMIT','CHAR-FONT-LIMIT','COMPLEX','COMPUTE-RESTARTS','CONTINUE','DECLAIM','DECLARE','DEFCLASS','DEFCONSTANT','DEFGENERIC','DEFINE-CONDITION','DEFINE-METHOD-COMBINATION','DEFINE-MODIFY-MACRO','DEFINE-SETF-EXPANDER','DEFMETHOD','DEFPACKAGE','DEFSETF','DEFSTRUCT','DEFTYPE','DESTRUCTURING-BIND','DIRECTORY','ECHO-STREAM-INPUT-STREAM','ECHO-STREAM-OUTPUT-STREAM','ECHO-STREAM-P','ECASE','ERROR','FIND-RESTART','GET-SETF-EXPANSION','IGNORE-ERRORS','LAMBDA','LOAD-TIME-VALUE','LOCALLY','MAKE-CONDITION','MUFFLE-WARNING','PROCLAIM','PROVIDE','REQUIRE','RESTART-BIND','RESTART-CASE','RESTART-NAME','SIGNAL','STORE-VALUE','THE','TIME','TRACE','UNTRACE','USE-VALUE','WARN','WITH-CONDITION-RESTARTS','WITH-SIMPLE-RESTART',
    'LISP-IMPLEMENTATION-TYPE','LISP-IMPLEMENTATION-VERSION','DESCRIBE','ED','DRIBBLE','DISASSEMBLE','CERROR','DEFMACRO','DEFPARAMETER','CLASS-OF','CLASS-NAME','CHANGE-CLASS','BUILT-IN-CLASS','CALL-METHOD','CALL-NEXT-METHOD','COMPUTE-APPLICABLE-METHODS','ENSURE-GENERIC-FUNCTION','GENERIC-FUNCTION-LAMBDA-LIST','GENERIC-FUNCTION-METHODS','GENERIC-FUNCTION-NAME','COMPILER-MACRO-FUNCTION','DEFINE-COMPILER-MACRO','DYNAMIC-EXTENT','FTYPE','FUNCTION','BROADCAST-STREAM-P','BROADCAST-STREAM-STREAMS','CONCATENATED-STREAM-P','CONCATENATED-STREAM-STREAMS','FILE-STREAM-P','COPY-READTABLE','ENSURE-DIRECTORIES-EXIST','FCEILING','FFLOOR','FROUND','FTRUNCATE','MAKE-INSTANCE','MAKE-METHOD','METHOD-COMBINATION-ERROR','METHOD-FUNCTION','METHOD-GENERIC-FUNCTION','METHOD-SPECIALIZERS','NEXT-METHOD-P','NO-APPLICABLE-METHOD','NO-NEXT-METHOD','REINITIALIZE-INSTANCE','REMOVE-METHOD','SHARED-INITIALIZE','SLOT-BOUNDP','SLOT-EXISTS-P','SLOT-MAKUNBOUND','SLOT-UNBOUND','SLOT-VALUE','STANDARD-CLASS','STANDARD-OBJECT','STRUCTURE-CLASS','STRUCTURE-OBJECT','PPRINT-TABULAR','READ-CHAR-NO-HANG','READ-DELIMITED-LIST','READ-FROM-STRING','READ-PRESERVING-WHITESPACE','STRING-STREAM-P','SYNONYM-STREAM-P','SYNONYM-STREAM-SYMBOL','TWO-WAY-STREAM-INPUT-STREAM','TWO-WAY-STREAM-OUTPUT-STREAM','TWO-WAY-STREAM-P','MOST-NEGATIVE-SINGLE-FLOAT','MOST-POSITIVE-LONG-FLOAT','MOST-POSITIVE-SHORT-FLOAT','MOST-POSITIVE-SINGLE-FLOAT','SHORT-FLOAT-EPSILON','SHORT-FLOAT-NEGATIVE-EPSILON','SINGLE-FLOAT-EPSILON','SINGLE-FLOAT-NEGATIVE-EPSILON','MAKE-DISPATCH-MACRO-CHARACTER','SET-MACRO-CHARACTER','SET-PPRINT-DISPATCH','SET-SYNTAX-FROM-CHAR','READTABLE-CASE','PROGV','PSETQ','QUOTE','RATIONAL','RATIONALIZE','MAP-INTO','MAPCON','ROW-MAJOR-AREF','SOFTWARE-TYPE','SOFTWARE-VERSION','ROOM','STEP','USER-HOMEDIR-PATHNAME','OCTETS-TO-STRING','STRING-TO-OCTETS','TYPE','UPGRADED-ARRAY-ELEMENT-TYPE','UPGRADED-COMPLEX-PART-TYPE','OPTIMIZE','SPECIAL','NIL','T','WITH-ACCESSORS','WITH-COMPILATION-UNIT','WITH-INPUT-FROM-STRING','WITH-OPEN-STREAM','WITH-OUTPUT-TO-STRING','WITH-PPRINT-LOGICAL-BLOCK','WITH-SLOTS','WITH-STANDARD-IO-SYNTAX','MACHINE-TYPE','MACHINE-INSTANCE','MACHINE-VERSION','LONG-SITE-NAME','SHORT-SITE-NAME','LOAD-LOGICAL-PATHNAME-TRANSLATIONS','LOGICAL-PATHNAME-TRANSLATIONS',
    'LEAST-NEGATIVE-LONG-FLOAT','LEAST-NEGATIVE-NORMALIZED-DOUBLE-FLOAT','LEAST-NEGATIVE-NORMALIZED-LONG-FLOAT','LEAST-NEGATIVE-NORMALIZED-SHORT-FLOAT','LEAST-NEGATIVE-NORMALIZED-SINGLE-FLOAT','LEAST-NEGATIVE-SHORT-FLOAT','LEAST-NEGATIVE-SINGLE-FLOAT','LEAST-POSITIVE-LONG-FLOAT','LEAST-POSITIVE-NORMALIZED-DOUBLE-FLOAT','LEAST-POSITIVE-NORMALIZED-LONG-FLOAT','LEAST-POSITIVE-NORMALIZED-SHORT-FLOAT','LEAST-POSITIVE-NORMALIZED-SINGLE-FLOAT','LEAST-POSITIVE-SHORT-FLOAT','LEAST-POSITIVE-SINGLE-FLOAT','LONG-FLOAT-EPSILON','LONG-FLOAT-NEGATIVE-EPSILON','METHOD-LAMBDA-LIST','METHOD-QUALIFIERS','MACROLET','SYMBOL-MACROLET','NOTINLINE','INLINE'
]


def test_all_expected_functions_are_registered():
    """Ensure every symbol listed in EXPECTED_LISP_FUNCTIONS has a function binding in the environment."""
    # Reset state and create a fresh standard environment
    state.current_environment = None
    state.functions_loaded = False
    env = lispenv.setup_standard_environment()

    missing = []
    for name in EXPECTED_LISP_FUNCTIONS:
        sym = lisptype.LispSymbol(name)
        bound = env.find_func(sym)
        if bound is None:
            missing.append(name)

    found = len(EXPECTED_LISP_FUNCTIONS) - len(missing)
    # Log a short summary so test output shows how many bindings were found.
    logging.getLogger(__name__).info("Found %d Lisp function bindings; missing %d.", found, len(missing))

    assert not missing, f"Missing Lisp function bindings for: {', '.join(missing)}"
