"""Common Lisp class system (simplified CLOS).

This module implements a basic class system supporting:
- DEFCLASS: Define classes with slots
- MAKE-INSTANCE: Create instances
- Slot readers/writers
- Simplified method dispatch (single dispatch only)
- Basic inheritance (linear order)
"""

from dataclasses import dataclass, field
from typing import Dict, List, Optional, Any, Callable
from fclpy.lisptype import LispSymbol, T, NIL, is_truthy, LispProgramError

@dataclass
class SlotDefinition:
    """Definition of a single slot in a class."""
    name: LispSymbol
    type_spec: Optional[Any] = None
    initform: Optional[Any] = None
    # CLHS 7.5.3: a slot may declare more than one :initarg, and CLHS 7.1.2
    # says the *leftmost* one supplied in the initialization argument list
    # wins when more than one of a slot's declared initargs is given --
    # storing only the last-parsed :initarg silently ignored every earlier
    # one, so MAKE-INSTANCE calls using any but the last-declared name for
    # a slot never initialized it.
    initargs: List[LispSymbol] = field(default_factory=list)
    allocation: str = "instance"  # "instance" or "class"
    documentation: Optional[str] = None
    # CLHS 7.5.3: a slot may name any number of :reader/:writer/:accessor
    # generic functions -- each one is a separate DEFCLASS-time
    # ADD-METHOD, not a single accessor per slot, so these are lists.
    readers: List[LispSymbol] = field(default_factory=list)
    writers: List[LispSymbol] = field(default_factory=list)
    accessors: List[LispSymbol] = field(default_factory=list)
    # CLHS 7.2 (DEFSTRUCT slots only -- ordinary CLOS slots have no such
    # concept): true if this slot has no SETF-able place at all, not just
    # a missing writer function. structures/structure-00.lsp's test 12
    # checks `(fboundp '(setf accessor))` is NIL for one of these.
    read_only: bool = False
    # The environment DEFCLASS was evaluated in, captured so a slot's
    # initform (an unevaluated form) can later be evaluated the way CLHS
    # 7.1.2 wants -- lexically where the class was defined, not wherever
    # MAKE-INSTANCE/SHARED-INITIALIZE happen to run. None (the bootstrap
    # case, and any caller that builds a SlotDefinition directly) falls
    # back to the global environment when the initform is actually needed.
    definition_env: Optional[Any] = None

    def __repr__(self):
        return f"SlotDefinition({self.name.name})"


def _topological_cpl(cls: 'LispClass') -> List['LispClass']:
    """The class precedence list of `cls` (CLHS 4.3.5, 4.3.5.1): a
    deterministic topological sort of `cls` and its superclasses with
    respect to the partial order generated by every class's local
    precedence order, with CLHS 4.3.5.1's tie-break -- "select the one
    that has a direct subclass rightmost in the class precedence list
    computed so far" -- and, when candidates still tie (two classes that
    are direct superclasses of the same most-recently-placed class, the
    way PARSE-ERROR and STREAM-ERROR both are of READER-ERROR), the
    candidate earliest in that class's own direct-superclass order.

    This is *not* C3: the two agree on single inheritance and on most
    diamonds, but C3's leftmost-local-order rule and CLHS's
    rightmost-direct-subclass rule diverge on nonmonotonic hierarchies --
    ansi-test's class-0306.1 builds one exactly to observe the difference
    (CLASS-0306C must precede CLASS-0306B in CLASS-0306H's CPL even
    though it *follows* it in the CPLs of H's direct superclasses), and
    C3 gets that wrong.
    """
    # SC: the set of cls and all its superclasses, collected so the
    # first-discovery order gives a deterministic fallback for ties the
    # spec's rule cannot separate.
    sc: List['LispClass'] = []
    seen = set()

    def collect(c: 'LispClass') -> None:
        if id(c) in seen:
            return
        seen.add(id(c))
        sc.append(c)
        for parent in c.direct_superclasses:
            collect(parent)

    collect(cls)

    # R: (x, y) pairs meaning "x precedes y", one per adjacent pair of
    # every class's local precedence order ([c, s1, s2, ...]). A class
    # with no predecessor in R may be placed next.
    predecessors: Dict[int, set] = {}
    for c in sc:
        chain = [c] + list(c.direct_superclasses)
        for i in range(len(chain) - 1):
            predecessors.setdefault(id(chain[i + 1]), set()).add(id(chain[i]))

    result: List['LispClass'] = []
    remaining = list(sc)
    while remaining:
        free = [c for c in remaining
                if not (predecessors.get(id(c), set()) - {id(p) for p in result})]
        if not free:
            names = ", ".join(c.name.name for c in remaining)
            raise LispProgramError(
                f"Inconsistent class precedence list for {cls.name.name} "
                f"-- cannot linearize among: {names}")
        if len(free) == 1:
            chosen = free[0]
        else:
            # CLHS 4.3.5.1's tie-break: the candidate that is a direct
            # superclass of the class placed *rightmost* in the result so
            # far. Several candidates may share that rightmost class
            # (READER-ERROR's two direct superclasses, say); the earliest
            # in that class's own direct-superclass list wins, and
            # first-discovery order is the final fallback.
            best_rank = None
            chosen = None
            for cand in free:
                supers = {id(p) for p in cand.direct_superclasses}
                rightmost = -1
                for pos, placed in enumerate(result):
                    if id(placed) in supers:
                        rightmost = pos
                rank = (rightmost, -_direct_super_position(cand, result),
                        -free.index(cand))
                if best_rank is None or rank > best_rank:
                    best_rank = rank
                    chosen = cand
        result.append(chosen)
        remaining.remove(chosen)
    return result


def _direct_super_position(cand: 'LispClass', result: List['LispClass']) -> int:
    """The position of the rightmost already-placed direct subclass of
    `cand` in `result`, or -1 when none is placed yet -- CLHS 4.3.5.1's
    `j`, used to break candidate ties."""
    for pos in range(len(result) - 1, -1, -1):
        if any(p is result[pos] for p in cand.direct_superclasses):
            return pos
    return -1


@dataclass
class LispClass:
    """Represents a Common Lisp class object.

    Stores slot definitions, parent classes, and class-level metadata.
    """
    name: LispSymbol
    direct_superclasses: List['LispClass'] = field(default_factory=list)
    direct_slots: List[SlotDefinition] = field(default_factory=list)
    class_slots: Dict[str, Any] = field(default_factory=dict)  # For class-allocated slots
    documentation: Optional[str] = None
    # CLHS 7.1.8: this class's own :default-initargs, as (initarg-name-symbol,
    # unevaluated-form, definition-env) triples. Never memoized to a value --
    # the form is evaluated fresh every MAKE-INSTANCE call that needs it (see
    # class-28 in objects/defclass-01.lsp, whose default form is `(incf y)`),
    # and only for an initarg name the call did not itself supply.
    direct_default_initargs: List[Any] = field(default_factory=list)
    # CLHS 7.3: bumped by MAKE-INSTANCES-OBSOLETE. An instance whose
    # `instance_generation` is behind this is obsolete and gets brought up to
    # date on its next slot access -- see `LispInstance.instance_generation`.
    # Excluded from __eq__: obsolescence is a state of the class object, not
    # part of what makes two classes the same class.
    instance_generation: int = field(default=0, compare=False)
    # Memoized class precedence list (see get_linearized_superclasses). Not
    # part of the class's identity or value -- excluded from __eq__ -- and
    # never stale in practice because redefining a class (DEFCLASS re-run)
    # builds a brand new LispClass object rather than mutating this one.
    _cpl_cache: Optional[List['LispClass']] = field(
        default=None, repr=False, compare=False)
    # CLHS 4.3.7: which metaobject class this class object is itself an
    # instance of -- 'STANDARD-CLASS' for an ordinary DEFCLASS,
    # 'STRUCTURE-CLASS' for DEFSTRUCT. Answers `(typep (find-class 'x)
    # 'structure-class)` (structure-00.lsp test 14), which is a question
    # about the class *object*, not about its instances -- TYPEP's
    # existing LispClass/LispInstance branches only ever answer the
    # latter.
    metaclass_name: str = 'STANDARD-CLASS'
    # CLHS 4.3.7 / MOP: True while this class exists only because some other
    # class named it as a superclass before it was defined -- a
    # *forward-referenced class*. It has no slots and no superclasses yet, and
    # it is not finalized, so no instance of it or of anything below it can be
    # made until a DEFCLASS fills it in (`define_forward_referenced_class`).
    # Excluded from __eq__ for the same reason `instance_generation` is: it is
    # a lifecycle state, not part of what makes two classes the same class.
    forward_referenced: bool = field(default=False, compare=False)

    def unfinalized_superclasses(self) -> List['LispClass']:
        """Every still-undefined forward-referenced class at or above `self`.

        A class whose superclass is merely *named* cannot be finalized (CLHS
        4.3.6), so this is what MAKE-INSTANCE checks before allocating.
        Walks `direct_superclasses` directly rather than the CPL, because
        computing the CPL is itself one of the things that cannot be done
        while a forward reference is outstanding.
        """
        pending, seen, out = [self], set(), []
        while pending:
            cls = pending.pop()
            if id(cls) in seen:
                continue
            seen.add(id(cls))
            if cls.forward_referenced:
                out.append(cls)
            pending.extend(cls.direct_superclasses)
        return out

    def get_linearized_superclasses(self) -> List['LispClass']:
        """This class's class precedence list (CLHS 4.3.5), most specific
        first: `self`, then its ancestors in the order CLHS 4.3.5.1's
        topological sort computes. Callers (specificity ordering, slot
        inheritance, SUBTYPEP's class cone) all depend on this being the
        actual CPL, not merely the set of ancestors.
        """
        if self._cpl_cache is None:
            self._cpl_cache = _topological_cpl(self)
        return self._cpl_cache
    
    def get_all_slots(self) -> Dict[str, SlotDefinition]:
        """Get all slots (direct and inherited) as a dict by slot name.

        Returns:
            Dictionary mapping slot name -> SlotDefinition

        CLHS 7.5.3: slot descriptions are gathered in class-precedence-list
        order, most specific first. For each slot name, the slot in the
        most specific class that provides it is the base; the **initform**
        is the one from the most specific class that provides *an
        initform* (a class that redeclares the slot without one does not
        shadow an ancestor's initform -- class-0302.1 pins exactly this),
        the **initargs** are the union over the whole CPL, and
        :reader/:writer/:accessor names accumulate the same way.
        """
        merged: Dict[str, Dict[str, Any]] = {}

        for cls in self.get_linearized_superclasses():
            for slot in cls.direct_slots:
                slot_name = slot.name.name
                if slot_name not in merged:
                    merged[slot_name] = {
                        'name': slot.name,
                        'type_spec': slot.type_spec,
                        'initform': slot.initform,
                        'initform_env': slot.definition_env,
                        'initargs': list(slot.initargs),
                        'allocation': slot.allocation,
                        'documentation': slot.documentation,
                        'readers': list(slot.readers),
                        'writers': list(slot.writers),
                        'accessors': list(slot.accessors),
                        'read_only': slot.read_only,
                    }
                    continue
                m = merged[slot_name]
                if m['initform'] is None and slot.initform is not None:
                    m['initform'] = slot.initform
                    m['initform_env'] = slot.definition_env
                m['initargs'].extend(slot.initargs)
                for readers_key in ('readers', 'writers', 'accessors'):
                    existing = m[readers_key]
                    for item in getattr(slot, readers_key):
                        if not any(item is e or item == e for e in existing):
                            existing.append(item)

        return {
            name: SlotDefinition(
                name=m['name'],
                type_spec=m['type_spec'],
                initform=m['initform'],
                initargs=m['initargs'],
                allocation=m['allocation'],
                documentation=m['documentation'],
                readers=m['readers'],
                writers=m['writers'],
                accessors=m['accessors'],
                read_only=m['read_only'],
                definition_env=m['initform_env'],
            )
            for name, m in merged.items()
        }

    def find_slot_definition_class(self, slot_name: str) -> Optional['LispClass']:
        """Find which class in the hierarchy originally defined a slot.

        For class-allocated slots, all instances of a class and its subclasses
        share the slot storage on the class that defined it. This method finds
        that defining class so SLOT-VALUE can access the correct class_slots dict.
        """
        for cls in self.get_linearized_superclasses():
            for slot in cls.direct_slots:
                if slot.name.name == slot_name:
                    return cls
        return None

    def get_all_default_initargs(self) -> Dict[str, Any]:
        """CLHS 7.1.8 point 2: the default initargs in effect for this class
        are the union, over the class precedence list, of each class's own
        `direct_default_initargs` -- when the same initarg name is declared
        by more than one class in the list, the one belonging to the *most
        specific* class wins. `get_linearized_superclasses()` is already
        most-specific-first (`self` is its own first element), so a plain
        first-occurrence-wins fold over it is that rule.

        Returns:
            Dict mapping initarg name -> (initarg-symbol, form, definition_env)
        """
        result: Dict[str, Any] = {}
        for cls in self.get_linearized_superclasses():
            for initarg_sym, form, def_env in cls.direct_default_initargs:
                key = initarg_sym.name if isinstance(initarg_sym, LispSymbol) else str(initarg_sym)
                if key not in result:
                    result[key] = (initarg_sym, form, def_env)
        return result

    def __repr__(self):
        return f"#<STANDARD-CLASS {self.name.name}>"


@dataclass
class LispInstance:
    """Represents an instance of a Common Lisp class.
    
    Stores the class reference and slot values.
    """
    lisp_class: LispClass
    slot_values: Dict[str, Any] = field(default_factory=dict)
    # CLHS 7.3: MAKE-INSTANCES-OBSOLETE does not touch existing instances --
    # each is brought up to date lazily, the next time a slot of it is
    # accessed, by UPDATE-INSTANCE-FOR-REDEFINED-CLASS. This records which
    # generation of its class the instance was last updated for; when it
    # differs from the class's own `instance_generation` the instance is
    # obsolete. An eager implementation would have to keep a registry of every
    # live instance of every class, which is a leak.
    instance_generation: int = 0

    def __repr__(self):
        return f"#<{self.lisp_class.name.name} {id(self)}>"
    
    def __str__(self):
        return repr(self)


class ClassRegistry:
    """Global registry of defined classes."""
    
    def __init__(self):
        self._classes: Dict[str, LispClass] = {}
    
    def register_class(self, cls: LispClass) -> LispClass:
        """Register a class in the registry."""
        self._classes[cls.name.name] = cls
        return cls

    def invalidate_cpl_caches(self) -> None:
        """Drop every memoized class precedence list.

        Called when a forward-referenced class is defined: any CPL computed
        while it was an empty placeholder was computed from the wrong
        superclass list. See `define_forward_referenced_class`.
        """
        for cls in self._classes.values():
            cls._cpl_cache = None

    def register_class_as(self, name: str, cls: LispClass) -> LispClass:
        """Register `cls` under `name` as an alias, without touching
        `cls.name`. `(setf (find-class alias) cls)` (CLHS) adds another
        name for an *existing* class; it does not rename it, so this must
        not go through `register_class`, which keys off the object's own
        mutable `.name` and would have to mutate it there and back to
        register under a different key -- a dance that corrupts the
        registry when two such aliasing operations touch the same
        objects in sequence (ROTATEF's own two SETFs-in-effect being
        exactly that case).
        """
        self._classes[name] = cls
        return cls

    def find_class(self, name: str) -> Optional[LispClass]:
        """Find a class by name."""
        return self._classes.get(name)

    def unregister_class_as(self, name: str) -> None:
        """Make `name` no longer denote a class (CLHS `(setf find-class)`,
        new-value NIL). A no-op if `name` was not registered -- the
        operation's own postcondition, `(find-class name nil)` is NIL, is
        already true either way.
        """
        self._classes.pop(name, None)

    def get_class_or_error(self, name: str) -> LispClass:
        """Find a class by name or raise error."""
        cls = self.find_class(name)
        if cls is None:
            raise NameError(f"Class not found: {name}")
        return cls
    
    def list_classes(self) -> List[LispClass]:
        """List all registered classes."""
        return list(self._classes.values())


# Global class registry
_class_registry = ClassRegistry()


def register_class(cls: LispClass) -> LispClass:
    """Register a class in the global registry."""
    return _class_registry.register_class(cls)


def ensure_forward_referenced_class(name: LispSymbol) -> LispClass:
    """The class named `name`, creating a *forward-referenced* placeholder for
    it if nothing is defined under that name yet (CLHS 4.3.7).

    This is what makes `(defclass a (b) ())` legal before `b` exists. The
    placeholder is a real, registered `LispClass`, so the subclass's
    `direct_superclasses` holds a class object like every other entry --
    `eval_defclass` used to append the bare *symbol* there instead, leaving a
    superclass list that was part classes and part symbols. Nothing resolved
    it later, so `(typep instance-of-a 'b)` was NIL forever and the CPL walk
    tripped over a symbol where a class was expected.

    Identity is the point: the placeholder object is the one
    `define_forward_referenced_class` later fills in, so every subclass
    already pointing at it sees the definition without being re-linked.
    """
    existing = _class_registry.find_class(name.name)
    if existing is not None:
        return existing
    placeholder = LispClass(name=name, forward_referenced=True)
    return _class_registry.register_class(placeholder)


def define_forward_referenced_class(placeholder: LispClass, **attributes) -> LispClass:
    """Turn a forward-referenced placeholder into a real class, in place.

    The MOP describes this as CHANGE-CLASSing the forward-referenced-class
    into a standard-class; the observable requirement is only that the object
    keeps its identity, because `(defclass c2 () ())` must return the very
    object that an earlier `(defclass c1 (c2) ())` linked to -- ansi-test
    checks `(typep i1 class2)` where `class2` is DEFCLASS's return value.
    Building a fresh object and re-registering it would leave `c1` pointing at
    the abandoned placeholder.
    """
    for attribute, value in attributes.items():
        setattr(placeholder, attribute, value)
    placeholder.forward_referenced = False
    # Every CPL computed while this class was still a placeholder was computed
    # from an empty superclass list and is now wrong. The memo's own comment
    # says it is "never stale in practice because redefining a class builds a
    # brand new LispClass object" -- filling a forward reference in place is
    # precisely the case that breaks that assumption, so the caches go. Doing
    # it registry-wide rather than tracking subclass back-pointers: this runs
    # once per forward reference resolved, and cannot miss a subclass.
    _class_registry.invalidate_cpl_caches()
    return placeholder


def register_class_as(name, cls: LispClass) -> LispClass:
    """Register `cls` under `name` as an alias, without renaming it --
    see `ClassRegistry.register_class_as`. `name` may be a symbol or a
    plain string.
    """
    if isinstance(name, LispSymbol):
        name = name.name
    return _class_registry.register_class_as(name, cls)


def unregister_class_as(name) -> None:
    """Make `name` no longer denote a class -- see `ClassRegistry.unregister_class_as`.
    `name` may be a symbol or a plain string.
    """
    if isinstance(name, LispSymbol):
        name = name.name
    _class_registry.unregister_class_as(name)


def find_class(name: str) -> Optional[LispClass]:
    """Find a class by name."""
    if isinstance(name, LispSymbol):
        name = name.name
    return _class_registry.find_class(name)


def resolve_class_designator(spec: Any) -> Any:
    """Resolve a MAKE-INSTANCE-style class designator (CLHS 7.1): a symbol
    or string names a class and must resolve to one. Anything else --
    already a class object, or any other value a DEFMETHOD chooses to
    specialize MAKE-INSTANCE's first parameter on -- passes through
    unchanged, so a method dispatching on some other type still matches
    it (ansi-test's make-instance.lsp defines one specialized on an
    *instance*, purely to exercise that dispatch on this argument works at
    all).

    Shared by `lispfunc.classes.make_instance` (the entry point for a
    direct Python call, which the unit-test suite makes) and
    `lispfunc.misc_clos._default_make_instance` (the entry point for every
    ordinary Lisp-level `(make-instance ...)` call, since evaluating even
    one DEFMETHOD on MAKE-INSTANCE replaces its *entire* environment
    binding with the bare GenericFunction object -- see plan.md's CLOS
    consolidation notes -- bypassing the Python wrapper from then on).
    """
    if isinstance(spec, LispSymbol):
        cls = find_class(spec.name)
        if cls is None:
            raise NameError(f"Class not found: {spec.name}")
        return cls
    if isinstance(spec, str):
        cls = find_class(spec)
        if cls is None:
            raise NameError(f"Class not found: {spec}")
        return cls
    return spec


def make_class(
    name: LispSymbol,
    direct_superclasses: Optional[List[LispClass]] = None,
    direct_slots: Optional[List[SlotDefinition]] = None,
    documentation: Optional[str] = None,
    direct_default_initargs: Optional[List[Any]] = None,
    metaclass_name: str = 'STANDARD-CLASS'
) -> LispClass:
    """Create a new class.

    Args:
        name: Symbol naming the class
        direct_superclasses: List of parent classes
        direct_slots: List of SlotDefinition objects
        documentation: Documentation string
        direct_default_initargs: List of (initarg-symbol, form, definition_env)
            triples from this class's own :default-initargs option (CLHS 7.1.8)
        metaclass_name: 'STANDARD-CLASS' (DEFCLASS) or 'STRUCTURE-CLASS'
            (DEFSTRUCT) -- see LispClass.metaclass_name.

    Returns:
        The created LispClass object
    """
    if direct_superclasses is None:
        direct_superclasses = []
    if direct_slots is None:
        direct_slots = []
    if direct_default_initargs is None:
        direct_default_initargs = []

    cls = LispClass(
        name=name,
        direct_superclasses=direct_superclasses,
        direct_slots=direct_slots,
        documentation=documentation,
        direct_default_initargs=direct_default_initargs,
        metaclass_name=metaclass_name
    )

    return cls


def make_instance(
    class_name: str,
    **initargs
) -> LispInstance:
    """MAKE-INSTANCE function: create an instance of a class.
    
    Args:
        class_name: Name of the class (as string or symbol)
        **initargs: Initialization arguments (keyword -> value)
    
    Returns:
        A new LispInstance object
    """
    if isinstance(class_name, LispSymbol):
        class_name = class_name.name
    
    cls = _class_registry.get_class_or_error(class_name)
    
    # Create instance
    instance = LispInstance(lisp_class=cls)
    
    # Get all slots (inherited and direct)
    all_slots = cls.get_all_slots()
    
    # Initialize slots
    for slot_name, slot_def in all_slots.items():
        value = None
        
        # Check if initarg was provided (leftmost-declared wins, CLHS 7.1.2)
        for initarg_sym in slot_def.initargs:
            arg_name = initarg_sym.name if isinstance(initarg_sym, LispSymbol) else initarg_sym
            if arg_name in initargs:
                value = initargs[arg_name]
                break
        
        # Use initform if no value provided
        if value is None and slot_def.initform is not None:
            value = slot_def.initform
        
        # Store the value
        instance.slot_values[slot_name] = value
    
    return instance


# Generic function support
#
# This is the *one* generic-function/method mechanism in fclpy. DEFGENERIC
# and DEFMETHOD (fclpy/lispfunc/evaluation_special_forms.py) build directly
# on ensure_generic_function/add_method/call_generic_function below, rather
# than each rolling its own dispatcher -- they used to (plan.md Finding L:
# "two CLOS implementations coexist"), which is also why CALL-NEXT-METHOD
# used to raise "No next method available" unconditionally: the dispatcher
# that actually ran a DEFMETHOD-defined method never populated the next-
# method context this module's CALL-NEXT-METHOD reads.


class EqlSpecializer:
    """An `(eql form)` specializer (CLHS 7.6.2): matches an argument by EQL
    to one specific object, evaluated once when the method is defined."""
    __slots__ = ('value',)

    def __init__(self, value):
        self.value = value

    def __repr__(self):
        return f"#<EQL-SPECIALIZER {self.value!r}>"


@dataclass(eq=False)
class Method:
    """A method in a generic function.

    `specializers` holds one entry per specializable (required) parameter:
    `None` for T/unspecialized, a `LispClass`, an `EqlSpecializer`, or a raw
    type-name symbol that named no modeled class (matched via TYPEP).
    `qualifiers` holds the method's raw qualifier objects (e.g. one
    `:before` keyword) -- CLHS 7.6.6.2's standard method combination reads
    their names to decide primary/before/after/around role.

    `eq=False` keeps the dataclass's default (identity-based, hashable)
    `__eq__`/`__hash__` instead of the field-wise ones `@dataclass` would
    otherwise generate. A field-wise `__eq__` also makes a class unhashable
    unless told not to (Python sets `__hash__ = None` alongside a generated
    `__eq__`), and a GENERIC-FUNCTION's methods are ordinary Lisp function
    values that the evaluator's `get_func_signature_info` caches keyed
    partly on the callable object itself -- `TypeError: unhashable type` as
    the value of *any* call to a method-carrying generic function is what
    that produces, not a niche corner case.
    """
    specializers: List[Any]
    function: Callable
    qualifiers: List[Any] = field(default_factory=list)
    generic_function: Optional['GenericFunction'] = None
    lambda_list: Optional[Any] = None
    # CLHS 7.6.2 / 25.1.3: a DEFMETHOD body may open with a documentation
    # string; `(documentation method t)` reads it back. `_make_method_function`
    # already extracts it via `split_function_body` -- this field is where the
    # extracted value is stored instead of being discarded.
    documentation: Optional[str] = None


@dataclass(eq=False)
class GenericFunction:
    """A generic function: a name, a lambda-list, a set of methods, and the
    method combination that decides how those methods are assembled into an
    effective method (CLHS 7.6.6).

    `method_combination` is None until DEFGENERIC's `:method-combination`
    option supplies one, and None means *standard* combination -- not "no
    combination". Resolving it lazily rather than storing STANDARD here
    keeps `ensure_generic_function` free of an import cycle back into the
    combination registry, which is populated after this class is defined.
    """
    name: LispSymbol
    methods: List[Method] = field(default_factory=list)
    documentation: Optional[str] = None
    lambda_list: Optional[Any] = None
    method_combination: Optional['MethodCombination'] = None
    # CLHS 7.6.6.1: the order required parameters are compared in when
    # ordering applicable methods -- a permutation of the lambda list's
    # required parameters, set by DEFGENERIC/ENSURE-GENERIC-FUNCTION's
    # :argument-precedence-order option. None means left-to-right (the
    # default). Stored as a list of *positions* into the specializer list,
    # so `_specificity_key` can permute without re-resolving names per call.
    argument_precedence_order: Optional[List[int]] = None

    def __repr__(self):
        return f"#<STANDARD-GENERIC-FUNCTION {generic_function_key(self.name)}>"

    def __call__(self, *args):
        # Makes a GenericFunction usable anywhere an ordinary callable is
        # (FUNCALL/APPLY, mapped over by MAPCAR, ...) instead of needing a
        # separate "is this a generic function?" branch at every call site.
        return call_generic_function(self, list(args))


def generic_function_key(name: Any) -> str:
    """The registry key for a *function name* (CLHS glossary): a symbol, or a
    `(SETF symbol)` list.

    The one place that key is computed. `register_generic` used to spell it
    `gf.name.name` while `ensure_generic_function` spelled it
    `name.name if isinstance(name, LispSymbol) else str(name)` -- two
    computations of the same key, and they disagreed for exactly the case that
    matters: a `(SETF accessor)` name is a **cons**, so registering a writer
    generic function raised ``AttributeError: 'lispCons' object has no
    attribute 'name'``. DEFCLASS defines a writer for every `:accessor` slot,
    so that killed `(defclass ... (:accessor ...))` outright -- and because it
    was raised while a file was being LOADed, and LOAD used to swallow
    per-form errors, it was invisible: ~700 tests in `objects/` simply never
    registered.

    Goes through `utilities_functions._function_spec_to_key`, the existing
    function-name resolver, so a setf generic function is keyed the same way
    the function registry keys a setf DEFUN.
    """
    from fclpy.lispfunc.utilities_functions import _function_spec_to_key
    key = _function_spec_to_key(name)
    if key is not None:
        return key.name
    return name.name if isinstance(name, LispSymbol) else str(name)


class GenericFunctionRegistry:
    """Global registry of generic functions."""

    def __init__(self):
        self._generics: Dict[str, GenericFunction] = {}

    def register_generic(self, gf: GenericFunction) -> GenericFunction:
        """Register a generic function."""
        self._generics[generic_function_key(gf.name)] = gf
        return gf

    def find_generic(self, name: str) -> Optional[GenericFunction]:
        """Find a generic function by name."""
        return self._generics.get(name)

    def get_generic_or_error(self, name: str) -> GenericFunction:
        """Find a generic function or raise error."""
        gf = self.find_generic(name)
        if gf is None:
            raise NameError(f"Generic function not found: {name}")
        return gf

    def list_generics(self) -> List[GenericFunction]:
        """List all registered generic functions."""
        return list(self._generics.values())


# Global generic function registry
_generic_registry = GenericFunctionRegistry()


def _required_param_count(lambda_list: Any) -> int:
    """How many required (specializable) parameters a generic-function
    lambda list declares. Shares the one lambda-list parser
    (`evaluation_core.parse_lambda_list`) rather than re-walking the list
    here, so this agrees with what DEFUN/DEFMACRO/DEFMETHOD already call
    "required"."""
    from fclpy.lispfunc.evaluation_core import parse_lambda_list
    return len(parse_lambda_list(lambda_list).get('required', []))


def ensure_generic_function(
    name: LispSymbol,
    documentation: Optional[str] = None,
    lambda_list: Optional[Any] = None,
) -> GenericFunction:
    """ENSURE-GENERIC-FUNCTION: get or create a generic function.

    Keyed by name string rather than symbol identity, so a DEFMETHOD in one
    package and a DEFGENERIC in another that both name the (inherited,
    non-shadowed) standard symbol SHARED-INITIALIZE resolve to the same
    generic function -- the way CALL-GENERIC-FUNCTION/ADD-METHOD already
    expected before this function existed.

    Args:
        name: Symbol naming the generic function
        documentation: Documentation string, set only if provided
        lambda_list: Lambda list, set only if provided (DEFGENERIC re-sets
            it every time it runs; DEFMETHOD alone never supplies one)

    Returns:
        The generic function (newly created or existing)
    """
    name_str = generic_function_key(name)

    gf = _generic_registry.find_generic(name_str)
    if gf is None:
        gf = GenericFunction(name=name)
        _generic_registry.register_generic(gf)

    if documentation is not None:
        gf.documentation = documentation
    if lambda_list is not None:
        # CLHS 7.6.4: every method's specializers must be congruent with
        # the generic function's own lambda list, in particular have one
        # specializer per required parameter. Re-running DEFGENERIC with a
        # lambda list whose required-parameter count differs from before
        # (`(defgeneric g (x) ...)` then `(defgeneric g (x y) ...)`) makes
        # every method added under the old arity incongruent with the new
        # one -- there is no longer a correspondence between its
        # specializers and the parameter list -- so it can no longer apply
        # and is discarded, the same way a freshly created generic function
        # would start with none. Without this, `add_method`'s specializer
        # count and the call's argument count can permanently disagree, and
        # `_matches_specializers`' "at least this many arguments" rule
        # (needed for methods with &optional/&rest of their own) then lets
        # the stale short method keep matching every call.
        if gf.lambda_list is not None and gf.methods:
            if _required_param_count(gf.lambda_list) != _required_param_count(lambda_list):
                gf.methods = []
        gf.lambda_list = lambda_list

    return gf


def _specializer_eq(a: Any, b: Any) -> bool:
    """Congruence test for two specializers (CLHS 7.6.3): adding a method
    whose qualifiers and specializers are congruent to an existing method
    replaces it rather than adding a second, shadowed copy -- without this,
    re-evaluating a DEFMETHOD (routine while iterating on one) piles up
    duplicates that all still fire."""
    if a is None or b is None:
        return a is b
    if isinstance(a, EqlSpecializer) and isinstance(b, EqlSpecializer):
        from fclpy.lispfunc.comparison import eql as _eql
        return _eql(a.value, b.value) is T
    if isinstance(a, LispClass) and isinstance(b, LispClass):
        return a is b
    if isinstance(a, LispSymbol) and isinstance(b, LispSymbol):
        return a.name.upper() == b.name.upper()
    return a == b


def _specializers_congruent(a_list: List[Any], b_list: List[Any]) -> bool:
    if len(a_list) != len(b_list):
        return False
    return all(_specializer_eq(x, y) for x, y in zip(a_list, b_list))


def _qualifier_names(method: 'Method') -> set:
    """Upcased, colon-stripped qualifier names, used only to decide the
    method's standard-method-combination role -- introspection
    (METHOD-QUALIFIERS) reads `method.qualifiers` itself, unnormalized."""
    names = set()
    for q in method.qualifiers:
        n = q.name if hasattr(q, 'name') else str(q)
        names.add(n.upper().lstrip(':'))
    return names


def add_method(
    generic_function: GenericFunction,
    specializers: List[Any],
    method_function: Callable,
    qualifiers: Optional[List[Any]] = None,
    lambda_list: Optional[Any] = None,
) -> GenericFunction:
    """ADD-METHOD: add a method to a generic function.

    Replaces any existing method with congruent qualifiers and specializers
    (CLHS 7.6.3) instead of appending a duplicate. Methods are stored
    unsorted; `call_generic_function` sorts applicable methods by
    specificity at call time, since a class's specificity can change after
    the method was added (a later DEFCLASS widening the hierarchy).

    Args:
        generic_function: The generic function to add to
        specializers: One specializer per specializable parameter (None,
            a LispClass, an EqlSpecializer, or a raw type-name symbol)
        method_function: The actual method function
        qualifiers: Method qualifiers, e.g. [:before] -- () for a primary
            method
        lambda_list: The method's own lambda list, when it was written in
            Lisp (DEFMETHOD/DEFGENERIC) -- the CLHS 7.6.5 keyword-argument
            rule unions the keyword parameters of every applicable method,
            which needs each one's lambda list

    Returns:
        The generic function
    """
    qualifiers = list(qualifiers or [])
    new_method = Method(
        specializers=specializers,
        function=method_function,
        qualifiers=qualifiers,
        generic_function=generic_function,
        lambda_list=lambda_list,
    )
    for i, existing in enumerate(generic_function.methods):
        if existing.qualifiers == qualifiers and _specializers_congruent(existing.specializers, specializers):
            generic_function.methods[i] = new_method
            return generic_function
    generic_function.methods.append(new_method)
    return generic_function


def remove_method(generic_function: GenericFunction, method: Method) -> GenericFunction:
    """REMOVE-METHOD: drop one method object from a generic function. The
    removed method no longer belongs to any generic function (its
    method-generic-function is cleared) -- which is what lets ADD-METHOD
    tell "moving a removed method" (legal) from "stealing a live one"
    (CLHS add-method's exceptional situation)."""
    generic_function.methods = [m for m in generic_function.methods if m is not method]
    if method.generic_function is generic_function:
        method.generic_function = None
    return generic_function


def class_of(obj: Any) -> LispClass:
    """CLASS-OF (CLHS 7.1.1): the class object naming obj's class.

    Every object has a class, not only CLOS instances -- this used to
    answer the bare symbol T for anything that was not a LispInstance,
    which made it impossible to dispatch a method on any built-in type.
    The answer must also be *rankable*: method specificity compares
    specializer positions in the argument's own class precedence list, so
    `(class-of 5)` answering the T class instead of INTEGER, or the T
    class for a condition object, orders every applicable method wrong
    (the *-CPL tests observe exactly that ordering through the
    class-precedence-list-foo generic function).

    Each branch below is the class of one representation family. The
    final fallback maps the name `type_of` answered to a class, walking
    through a table of type names that have no class of their own (CLHS
    4.3.7 figure 4-8 lists every standardized class; BIT, FIXNUM,
    SIMPLE-STRING and friends are types without one) to the nearest
    standardized class that contains them.
    """
    if isinstance(obj, LispInstance):
        return obj.lisp_class
    # A class object is an instance of its metaclass (CLHS 4.3.7): the
    # built-in type classes here are instances of BUILT-IN-CLASS, a
    # DEFCLASS's product of STANDARD-CLASS, a DEFSTRUCT's of
    # STRUCTURE-CLASS -- answering T here left `(class-of 'symbol)` with
    # no metaclass to dispatch on at all.
    if isinstance(obj, LispClass):
        return find_class(getattr(obj, 'metaclass_name', 'STANDARD-CLASS')) \
            or find_class('T')
    # A generic function is an instance of the class its DEFGENERIC's
    # :generic-function-class option named (CLHS 7.7) -- STANDARD-GENERIC-
    # FUNCTION when the option is absent. Defgeneric.30 typep's the object
    # against both, so the recorded class must be the one CLASS-OF answers.
    if isinstance(obj, GenericFunction):
        return getattr(obj, 'gf_class', None) \
            or find_class('STANDARD-GENERIC-FUNCTION') \
            or find_class('T')
    # Conditions are plain Python classes (lisptype_extended.py), not
    # LispInstances; their built-in types are the ones this module
    # registers, in most-specific-first order, so the first isinstance
    # hit is the most specific modeled class.
    if isinstance(obj, _condition_base_class()):
        name = _condition_type_name_of(obj)
        if name is not None:
            cls = find_class(name)
            if cls is not None:
                return cls
    # Arrays have a compound TYPE-OF answer (`(simple-array t (2 3))`);
    # the class of one is decided by shape (CLHS 15.1.2 / 4.2.3): a rank-1
    # array of bits is a BIT-VECTOR, of characters a STRING, any other
    # rank-1 array a VECTOR, and a multi-dimensional array an ARRAY.
    if _is_lisp_array(obj):
        from fclpy.lispfunc import arrays as _arrays
        try:
            element = _arrays.element_type_of(obj)
            rank = _arrays.array_rank_of(obj)
        except Exception:
            element, rank = None, None
        if rank == 1:
            if element is _arrays.BIT_TYPE:
                return find_class('BIT-VECTOR') or find_class('T')
            if element is _arrays.CHARACTER_TYPE:
                return find_class('STRING') or find_class('T')
            return find_class('VECTOR') or find_class('T')
        return find_class('ARRAY') or find_class('T')
    if isinstance(obj, _lisp_string_class()):
        return find_class('STRING') or find_class('T')
    # `type_of` has no branch for Python rationals (they are not `int` and
    # not `float`), so a ratio would otherwise fall through to T.
    from fractions import Fraction as _Fraction
    if isinstance(obj, _Fraction):
        return find_class('RATIO') or find_class('T')
    name = _representation_name_of(obj)
    if name is not None:
        return find_class(name) or find_class('T')
    from fclpy.lispfunc.comparison import type_of as _type_of
    from fclpy.lispfunc.core import _consp_internal, car as _car
    result = _type_of(obj)
    if _consp_internal(result):
        result = _car(result)
    name = result.name if isinstance(result, LispSymbol) else str(result)
    return find_class(_NEAREST_CLASS_FOR_TYPELESS_NAME.get(name.upper(), name)) \
        or find_class('T')


def _is_lisp_array(obj: Any) -> bool:
    from fclpy.lispfunc.arrays import is_array
    return bool(is_array(obj))


def _lisp_string_class():
    from fclpy import lisptype
    return getattr(lisptype, 'LispString', ())


def _representation_name_of(obj: Any) -> Optional[str]:
    """The built-in class name of the remaining representation families
    `type_of` does not classify (streams, hash tables, pathnames, ...) --
    the same families CLHS 4.2 gives classes to, and the ones method
    dispatch on a STREAM/HASH-TABLE/... specializer needs ranked."""
    from fclpy.lispfunc.misc_hashtables import is_hash_table
    if is_hash_table(obj):
        return 'HASH-TABLE'
    from fclpy import lisptype
    if isinstance(obj, getattr(lisptype, 'Pathname', ())):
        return 'LOGICAL-PATHNAME' if getattr(obj, 'logical', False) else 'PATHNAME'
    from fclpy.readtable import Readtable
    if isinstance(obj, Readtable):
        return 'READTABLE'
    try:
        from fclpy.lispfunc.utilities_system import RandomState
        if isinstance(obj, RandomState):
            return 'RANDOM-STATE'
    except Exception:
        pass
    if isinstance(obj, Method):
        # A DEFMETHOD product is a STANDARD-METHOD (CLHS 7.6.2) -- the class
        # `_init_builtin_classes` registers, so CLASS-OF answers a real class
        # and method dispatch on METHOD/STANDARD-METHOD specializers ranks.
        return 'STANDARD-METHOD'
    from fclpy.lispfunc import streams as _streams
    for cls, name in _STREAM_CLASS_NAMES:
        pycls = getattr(_streams, cls, None)
        if isinstance(pycls, type) and isinstance(obj, pycls):
            return name
    return None


# streams.py's Python stream classes -> their CLHS 21.2 class names, most
# specific first. (The module cannot be imported eagerly here: it lives
# above classes.py in the bootstrap's import order.) The base `Stream` is
# last: `*standard-output*` and friends are bare `Stream` instances, and
# with no entry for them CLASS-OF answered the T class.
_STREAM_CLASS_NAMES = (
    ('StringInputStream', 'STRING-STREAM'),
    ('StringOutputStream', 'STRING-STREAM'),
    ('FillPointerOutputStream', 'STRING-STREAM'),
    ('TwoWayStream', 'TWO-WAY-STREAM'),
    ('EchoStream', 'ECHO-STREAM'),
    ('ConcatenatedStream', 'CONCATENATED-STREAM'),
    ('BroadcastStream', 'BROADCAST-STREAM'),
    ('SynonymStream', 'SYNONYM-STREAM'),
    ('Stream', 'STREAM'),
)


_condition_python_class_names: Dict[int, str] = {}


def _condition_base_class():
    """`lisptype.Condition`, fetched lazily (classes.py must stay importable
    before the condition object model exists -- the bootstrap imports this
    module first)."""
    from fclpy import lisptype
    return getattr(lisptype, 'Condition', ())


def _condition_type_name_of(obj: Any) -> Optional[str]:
    """The name of the most specific *modeled* (built-in) condition class
    `obj` is an instance of, or None. User DEFINE-CONDITION types have no
    LispClass here, so their instances answer their nearest built-in
    ancestor -- the same answer method dispatch would compute, since the
    built-in class specializers are the only ones a generic function can
    carry for them."""
    if not _condition_python_class_names:
        # Reverse map: built-in condition LispClass name -> the Python
        # class `evaluation_conditions` models it with.
        from fclpy.lispfunc.evaluation_conditions import _condition_class_for_name
        for name in _CONDITION_NAMES_MOST_SPECIFIC_FIRST:
            pycls = _condition_class_for_name(name)
            if isinstance(pycls, type):
                _condition_python_class_names[id(pycls)] = name
    for klass in type(obj).__mro__:
        name = _condition_python_class_names.get(id(klass))
        if name is not None:
            return name
    return None


# Type names with no standardized class of their own (CLHS 4.3.7: only the
# names in figure 4-8 have classes) mapped to the nearest standardized class
# containing them -- `class_of`'s fallback for the names `type_of` answers.
_NEAREST_CLASS_FOR_TYPELESS_NAME = {
    'BIT': 'INTEGER', 'FIXNUM': 'INTEGER', 'BIGNUM': 'INTEGER',
    'SIGNED-BYTE': 'INTEGER', 'UNSIGNED-BYTE': 'INTEGER',
    'SIMPLE-STRING': 'STRING', 'SIMPLE-BASE-STRING': 'STRING',
    'BASE-STRING': 'STRING', 'SIMPLE-VECTOR': 'VECTOR',
    'SIMPLE-BIT-VECTOR': 'BIT-VECTOR', 'SIMPLE-ARRAY': 'ARRAY',
    'BASE-CHAR': 'CHARACTER', 'STANDARD-CHAR': 'CHARACTER',
    'EXTENDED-CHAR': 'CHARACTER', 'COMPILED-FUNCTION': 'FUNCTION',
    'BOOLEAN': 'SYMBOL',
}


def _arg_matches_specializer(arg: Any, spec: Any) -> bool:
    """Does one argument satisfy one specializer (CLHS 7.6.2)?"""
    if spec is None:
        return True
    if isinstance(spec, EqlSpecializer):
        from fclpy.lispfunc.comparison import eql as _eql
        return _eql(arg, spec.value) is T
    if isinstance(spec, LispClass):
        if isinstance(arg, LispInstance):
            return _is_instance_of(arg, spec)
        # A built-in-type specializer (INTEGER, STRING, ...) applied to a
        # non-instance: the argument's own class precedence list is the
        # primary answer -- the same list `_specializer_rank` orders by, so
        # what matches is exactly what ranks (a `classes.Method` object,
        # say, is a STANDARD-OBJECT via its STANDARD-METHOD class's CPL,
        # which the old typep-only check missed). TYPEP remains as a
        # fallback for the type names whose classes are more inclusive
        # than their CPL position (ATOM over numbers, ...).
        arg_class = class_of(arg)
        if isinstance(arg_class, LispClass):
            for cls in arg_class.get_linearized_superclasses():
                if cls is spec:
                    return True
        from fclpy.lispfunc.comparison import typep as _typep
        return _typep(arg, spec.name) is T
    # A specializer symbol that named no modeled LispClass at all (a CLHS
    # type this codebase has no class object for): still ask TYPEP, so any
    # type name is usable as a specializer, not only the ones in
    # _init_builtin_classes's list.
    from fclpy.lispfunc.comparison import typep as _typep
    return _typep(arg, spec) is T


def _matches_specializers(args: List[Any], specializers: List[Any]) -> bool:
    """Is a method with these specializers applicable to these call args?"""
    if len(specializers) > len(args):
        return False
    return all(_arg_matches_specializer(arg, spec) for arg, spec in zip(args, specializers))


def _specializer_rank(arg: Any, spec: Any) -> int:
    """Where one specializer falls in specificity order for one call
    argument (CLHS 7.6.6.1): lower sorts first, i.e. more specific.

    The rule is the same for *every* argument: the specializer's rank is
    its position in the argument's own class precedence list. For a
    `LispInstance` that is the instance's class's CPL; for any other
    object it is the CPL of the class `class_of` answers (INTEGER for an
    integer, STRING for a string, the condition class for a condition,
    the metaclass for a class object, ...). Ranking by the specializer's
    own ancestor count -- what this did before -- cannot order two
    specializers of different CPL depth correctly and orders same-depth
    ones not at all; the *-CPL tests observe the resulting order
    directly.

    An EQL specializer's rank must beat every class specializer's, no
    matter how deep that class's ancestor chain is (the scale is
    unbounded in principle), so it uses -inf/+inf sentinels rather than a
    fixed number that a long enough hierarchy could exceed."""
    if spec is None:
        return float('inf')
    if isinstance(spec, EqlSpecializer):
        return float('-inf')
    if isinstance(spec, LispClass):
        if isinstance(arg, LispInstance):
            cpl = arg.lisp_class.get_linearized_superclasses()
        else:
            arg_class = class_of(arg)
            if not isinstance(arg_class, LispClass):
                return len(spec.get_linearized_superclasses())
            cpl = arg_class.get_linearized_superclasses()
        for i, cls in enumerate(cpl):
            if cls is spec:
                return i
        return len(cpl)
    return 0


def _specificity_key(args: List[Any], specializers: List[Any],
                     apo: Optional[List[int]] = None) -> tuple:
    """A method's specificity key for this particular call, ascending =
    more specific first (CLHS 7.6.6.1): compare specializers position by
    position, most-specific-required-parameter first, exactly as CLHS
    defines method ordering. `apo` is the generic function's
    :argument-precedence-order permutation -- positions into the
    specializer list in the order they should be compared; None compares
    left-to-right."""
    if apo is not None:
        return tuple(_specializer_rank(args[i], specializers[i]) for i in apo)
    return tuple(_specializer_rank(arg, spec) for arg, spec in zip(args, specializers))


def _is_instance_of(instance: LispInstance, lisp_class: LispClass) -> bool:
    """Check if an instance is of a given class (including superclasses)."""
    for cls in instance.lisp_class.get_linearized_superclasses():
        if cls is lisp_class:
            return True
    return False


def _no_applicable_method(gf: GenericFunction, args: List[Any]):
    gf_name = gf.name.name if isinstance(gf.name, LispSymbol) else str(gf.name)
    raise LispProgramError(
        f"No applicable method for {gf_name} with arguments: {args}"
    )


class MakeMethod:
    """The method `(MAKE-METHOD form)` denotes (CLHS 7.6.6.2): a method with
    no qualifiers and no specializers whose body is one form.

    Method combination uses it to splice a computed sub-combination into a
    position that expects a method -- standard combination's before/primary/
    after core is passed to the innermost :around method this way -- so
    CALL-METHOD and the next-method chain have exactly *one* kind of thing
    to call rather than "a method, or else the special core closure".
    """
    __slots__ = ('function', 'qualifiers', 'specializers', 'generic_function', 'lambda_list')

    def __init__(self, function: Callable, generic_function: Optional[GenericFunction] = None):
        self.function = function
        self.qualifiers = []
        self.specializers = []
        self.generic_function = generic_function
        self.lambda_list = None

    def __repr__(self):
        return "#<METHOD (MAKE-METHOD)>"


# The dynamic (per-call, reentrant) CALL-NEXT-METHOD/NEXT-METHOD-P context:
# a stack of frames, one per method currently executing, so a method that
# itself triggers a nested generic-function call (directly, or by calling a
# different generic function that recurses back into this one) sees its own
# frame on top rather than a sibling call's -- a single flat "last call's
# next methods" slot (what this replaced) is exactly the kind of state a
# single-threaded interpreter with recursive calls cannot share safely.
#
# A frame is `{'args', 'next', 'gf'}` and there is only one *kind* of it:
# `next` is the ordered list of methods CALL-NEXT-METHOD may reach from
# here, empty when there is none. It used to carry a `kind` discriminator
# ('around'/'primary'/'none') with a separate `core` closure for the around
# chain, which is why NEXT-METHOD-P answered T inside every :around method
# whether or not anything remained, and why nothing but standard
# combination could ever build a chain at all.
_call_stack: List[Dict[str, Any]] = []


def call_method(method: Any, next_methods: List[Any], args: List[Any]) -> Any:
    """CALL-METHOD's operator (CLHS 7.6.6.2): invoke one method with
    `next_methods` as the chain CALL-NEXT-METHOD may walk from inside it.

    **This is the one place a method is ever invoked.** Standard
    combination, the short and long forms of DEFINE-METHOD-COMBINATION and
    the CALL-METHOD operator itself all bottom out here, so the
    next-method context cannot disagree between them.
    """
    _call_stack.append({
        'args': args,
        'next': list(next_methods),
        'gf': getattr(method, 'generic_function', None),
        'method': method,
    })
    try:
        return method.function(*args)
    finally:
        _call_stack.pop()


# Some generic functions (the CLOS metaobject protocol's ALLOCATE-INSTANCE/
# INITIALIZE-INSTANCE/SHARED-INITIALIZE/... -- see
# fclpy/lispfunc/misc_clos.py) are supposed to always have a default
# primary method installed by the module that owns them, not only a set of
# user-added ones. `_generic_registry` is a bare module-level dict nothing
# stops arbitrary code (deliberately, the unit-test suite, to isolate
# user-defined generics between tests) from clearing or replacing wholesale,
# which used to strand these "system" generic functions with no default
# and no way to recover one. A generic function with no methods at all
# self-heals here rather than at every call site that might reach it.
_default_method_installers: Dict[str, Callable[[GenericFunction], None]] = {}


def register_default_method_installer(name, installer: Callable[[GenericFunction], None]):
    """Register `installer(gf)` to (re-)populate a generic function's
    default method whenever it is found with none at all."""
    name_str = name.name if isinstance(name, LispSymbol) else str(name)
    _default_method_installers[name_str] = installer


def compute_applicable_methods(gf: GenericFunction, args: List[Any]) -> List[Method]:
    """Every method of `gf` applicable to `args`, most-specific-first (CLHS
    7.6.6.1) -- the one selection every caller uses, so COMPUTE-APPLICABLE-
    METHODS cannot disagree with what a real call would invoke."""
    if not isinstance(gf, GenericFunction):
        # Reached from the COMPUTE-APPLICABLE-METHODS operator, which any
        # value can be handed. Signalling beats letting Python's
        # AttributeError surface as the form's value (standing rule 2).
        raise LispProgramError(
            f"COMPUTE-APPLICABLE-METHODS: {gf!r} is not a generic function")
    applicable = [m for m in gf.methods if _matches_specializers(args, m.specializers)]
    # Ascending: _specificity_key ranks more-specific lower. Stable, so
    # methods still tied after a real CPL comparison (e.g. two specializers
    # on a built-in, non-instance type, which falls back to ancestor count)
    # keep definition order rather than an arbitrary one.
    applicable.sort(key=lambda m: _specificity_key(args, m.specializers,
                                                   gf.argument_precedence_order))
    return applicable


class MethodCombinationError(LispProgramError):
    """The condition METHOD-COMBINATION-ERROR names (CLHS 7.6.6.4): the
    applicable methods cannot be assembled into an effective method -- an
    unrecognized qualifier, or a required method group left empty."""


# ==============================================================================
# Method combination (CLHS 7.6.6)
# ==============================================================================
# A method combination *type* knows how to turn the applicable methods into
# an effective method. A method combination *object* is that type plus the
# options the generic function supplied in `(:method-combination name
# . options)`. The generic function holds the object; the registry below
# holds the types.
#
# Every type produces its effective method out of `call_method` above, so
# CALL-NEXT-METHOD, NEXT-METHOD-P and CALL-METHOD behave identically no
# matter which combination is in force. Standard combination assembles the
# chain in Python because its shape is fixed; the DEFINE-METHOD-COMBINATION
# forms assemble a Lisp *form* instead, because the operator they combine
# with may be a macro whose evaluation order is part of the semantics --
# `(and (call-method m1) (call-method m2))` must stop at the first NIL, and
# ansi-test observes exactly that.


class MethodCombinationType:
    """Base class: a named way of combining methods."""

    def __init__(self, name: LispSymbol, documentation: Optional[str] = None):
        self.name = name
        self.documentation = documentation

    @property
    def name_string(self) -> str:
        return self.name.name if isinstance(self.name, LispSymbol) else str(self.name)

    def invoke(self, gf: GenericFunction, applicable: List[Method],
               args: List[Any], options: List[Any]) -> Any:
        raise NotImplementedError

    def __repr__(self):
        return f"#<METHOD-COMBINATION {self.name_string}>"


class MethodCombination:
    """A method combination object: a type plus the (unevaluated) options
    one generic function gave it."""
    __slots__ = ('type', 'options')

    def __init__(self, type_: MethodCombinationType, options: Optional[List[Any]] = None):
        self.type = type_
        self.options = list(options or [])

    @property
    def name(self):
        return self.type.name

    @property
    def documentation(self):
        return self.type.documentation

    def invoke(self, gf: GenericFunction, applicable: List[Method], args: List[Any]) -> Any:
        return self.type.invoke(gf, applicable, args, self.options)

    def __repr__(self):
        return f"#<METHOD-COMBINATION {self.type.name_string}>"


class StandardMethodCombination(MethodCombinationType):
    """CLHS 7.6.6.2: :around methods outermost, then :before methods
    most-specific-first, the most specific applicable primary method (which
    may CALL-NEXT-METHOD into the rest), then :after methods
    least-specific-first."""

    def invoke(self, gf, applicable, args, options):
        primaries = [m for m in applicable if not m.qualifiers]
        befores = [m for m in applicable if _qualifier_names(m) == {'BEFORE'}]
        afters = [m for m in applicable if _qualifier_names(m) == {'AFTER'}]
        arounds = [m for m in applicable if _qualifier_names(m) == {'AROUND'}]

        recognized = ({'BEFORE'}, {'AFTER'}, {'AROUND'})
        for m in applicable:
            if m.qualifiers and _qualifier_names(m) not in recognized:
                raise MethodCombinationError(
                    f"{_gf_name(gf)}: standard method combination accepts only "
                    f":BEFORE, :AFTER and :AROUND qualifiers, not "
                    f"{[str(q) for q in m.qualifiers]}")

        def run_core(*_args):
            if not primaries:
                _no_applicable_method(gf, args)
            for m in befores:
                call_method(m, [], args)
            result = call_method(primaries[0], primaries[1:], args)
            for m in reversed(afters):
                call_method(m, [], args)
            return result

        if not arounds:
            return run_core()
        return call_method(arounds[0], arounds[1:] + [MakeMethod(run_core, gf)], args)


def _gf_name(gf) -> str:
    name = getattr(gf, 'name', gf)
    return name.name if isinstance(name, LispSymbol) else str(name)


def set_argument_precedence_order(gf: GenericFunction, lambda_list: Any,
                                  order_list: List[Any]) -> None:
    """Validate and install DEFGENERIC/ENSURE-GENERIC-FUNCTION's
    :argument-precedence-order option (CLHS 7.6.6.1): it must name each
    required parameter of the generic function's lambda list exactly once,
    in the order those parameters are compared when methods are ordered.
    Stored as *positions* into the specializer list, which is what
    `_specificity_key` consumes. One home, shared by both operators, so
    they cannot disagree on what is a valid permutation."""
    from fclpy.lispfunc.evaluation_core import parse_lambda_list
    required = []
    for param in parse_lambda_list(lambda_list).get('required', []):
        if isinstance(param, LispSymbol):
            required.append(param.name.upper())
    given = [p.name.upper() for p in order_list if isinstance(p, LispSymbol)]
    if (sorted(given) != sorted(required)
            or len(set(given)) != len(given)):
        raise LispProgramError(
            f":ARGUMENT-PRECEDENCE-ORDER {given} is not a permutation of "
            f"the required parameters {required}")
    gf.argument_precedence_order = [required.index(name) for name in given]


def _order_option(options: List[Any], default: str = 'MOST-SPECIFIC-FIRST') -> str:
    """The ordering a short-form combination was given in
    `(:method-combination name [order])` -- :MOST-SPECIFIC-FIRST (the
    default) or :MOST-SPECIFIC-LAST."""
    for opt in options:
        text = (opt.name if isinstance(opt, LispSymbol) else str(opt)).upper().lstrip(':')
        if text in ('MOST-SPECIFIC-FIRST', 'MOST-SPECIFIC-LAST'):
            return text
    return default


def _apply_order(methods: List[Any], order: str) -> List[Any]:
    return list(reversed(methods)) if order == 'MOST-SPECIFIC-LAST' else list(methods)


class ShortFormMethodCombination(MethodCombinationType):
    """The short form of DEFINE-METHOD-COMBINATION (CLHS), and with it the
    nine built-in combination types of CLHS 7.6.6.4.

    Every applicable method must be qualified either with the combination's
    own name (a *primary* method) or with :AROUND; the effective method is
    `(operator (call-method p1) (call-method p2) ...)` wrapped in the
    :AROUND chain. Building that as a real form rather than folding the
    results in Python is what makes the AND and OR combinations short-
    circuit, which is directly observable: ansi-test's
    DEFGENERIC-METHOD-COMBINATION.AND.1 asserts that the methods after the
    first NIL never run.
    """

    def __init__(self, name, operator=None, identity_with_one_argument=False,
                 documentation=None):
        super().__init__(name, documentation)
        self.operator = operator if operator is not None else name
        self.identity_with_one_argument = identity_with_one_argument

    def invoke(self, gf, applicable, args, options):
        from fclpy.lispfunc.sequence_protocol import make_lisp_list

        own = self.name_string.upper()
        primaries, arounds = [], []
        for m in applicable:
            names = _qualifier_names(m)
            if names == {own}:
                primaries.append(m)
            elif names == {'AROUND'}:
                arounds.append(m)
            else:
                raise MethodCombinationError(
                    f"{_gf_name(gf)}: the {own} method combination accepts only "
                    f"{own} and :AROUND qualifiers, not {[str(q) for q in m.qualifiers]}")

        if not primaries:
            raise MethodCombinationError(
                f"{_gf_name(gf)}: no applicable primary ({own}) method")

        primaries = _apply_order(primaries, _order_option(options))
        calls = [make_lisp_list([_CALL_METHOD_SYM, m]) for m in primaries]
        if self.identity_with_one_argument and len(calls) == 1:
            core = calls[0]
        else:
            core = make_lisp_list([self.operator] + calls)

        return _run_effective_method(gf, core, arounds, args)


class LongFormMethodCombination(MethodCombinationType):
    """The long form of DEFINE-METHOD-COMBINATION: `builder(gf, applicable,
    options)` answers `(form, env)`, the effective method the user's body
    computed. Parsing the method-group specifiers and the combination's own
    lambda list is the evaluator's job (see
    `evaluation_special_forms.eval_define_method_combination`), so this
    class holds no second copy of either."""

    def __init__(self, name, builder: Callable, documentation=None):
        super().__init__(name, documentation)
        self.builder = builder

    def invoke(self, gf, applicable, args, options):
        from fclpy.lispfunc.evaluation_core import eval as _eval
        form, env = self.builder(gf, applicable, options, args)
        _effective_context.append({'gf': gf, 'args': args, 'env': env})
        try:
            return _eval(form, env)
        finally:
            _effective_context.pop()


# The arguments of the generic-function call whose effective method *form*
# is currently being evaluated. CALL-METHOD reads its arguments from here
# rather than taking them as operands, because CLHS gives it none: an
# effective method is a function of the original call's arguments, and the
# combination that built the form does not name them.
_effective_context: List[Dict[str, Any]] = []

def _cl_symbol(name: str) -> LispSymbol:
    """The interned COMMON-LISP symbol of this name. A form built out of
    bare `LispSymbol(...)` objects would name *different* symbols from the
    ones the environment binds -- function and variable lookup is by symbol
    identity, not by name (see CLAUDE.md) -- so the `(PROGN ...)` an
    effective method is made of has to be the real PROGN."""
    from fclpy.lisptype import COMMON_LISP_PACKAGE
    return COMMON_LISP_PACKAGE.intern_symbol(name)


_CALL_METHOD_SYM = _cl_symbol('CALL-METHOD')


def _run_effective_method(gf, core_form, arounds, args):
    """Evaluate a combination-built effective method: `core_form` wrapped in
    `arounds` (most-specific-first), which is the same :AROUND chain
    standard combination builds -- one shape, not one per combination."""
    from fclpy.lispfunc.evaluation_core import eval as _eval
    import fclpy.state as _state

    # The form names only the combination's operator and CALL-METHOD, so the
    # global environment is the right (and only correct) place to resolve it
    # -- a short-form combination's operator is looked up where the
    # combination was defined, not wherever the call happens to originate.
    env = _state.current_environment

    def run_core(*call_args):
        _effective_context.append({'gf': gf, 'args': list(call_args) or args, 'env': env})
        try:
            return _eval(core_form, env)
        finally:
            _effective_context.pop()

    if not arounds:
        return run_core(*args)
    return call_method(arounds[0], arounds[1:] + [MakeMethod(run_core, gf)], args)


# ------------------------------------------------------------------ registry

_method_combination_types: Dict[str, MethodCombinationType] = {}


def register_method_combination_type(type_: MethodCombinationType) -> MethodCombinationType:
    """Install a method combination type under its name. DEFINE-METHOD-
    COMBINATION redefining an existing name replaces it here, which is what
    makes every generic function already using it pick the new definition
    up (they hold the *object*, which holds the type by reference)."""
    _method_combination_types[type_.name_string.upper()] = type_
    return type_


def find_method_combination_type(name) -> Optional[MethodCombinationType]:
    key = (name.name if isinstance(name, LispSymbol) else str(name)).upper()
    return _method_combination_types.get(key)


STANDARD_METHOD_COMBINATION = StandardMethodCombination(_cl_symbol('STANDARD'))
register_method_combination_type(STANDARD_METHOD_COMBINATION)

# CLHS 7.6.6.4's built-in combination types, each defined as if by the short
# form of DEFINE-METHOD-COMBINATION with itself as the operator. APPEND and
# LIST are the two that are *not* :identity-with-one-argument, which is
# observable: with a single applicable method, the LIST combination answers
# `(x)` and not `x`.
for _op, _identity in (('PROGN', True), ('AND', True), ('OR', True), ('+', True),
                       ('MAX', True), ('MIN', True), ('NCONC', True),
                       ('APPEND', False), ('LIST', False)):
    register_method_combination_type(
        ShortFormMethodCombination(_cl_symbol(_op), identity_with_one_argument=_identity))
del _op, _identity


def method_combination_of(gf: GenericFunction) -> MethodCombination:
    """The method combination in force for `gf` -- standard unless
    DEFGENERIC said otherwise."""
    comb = getattr(gf, 'method_combination', None)
    if comb is None:
        return MethodCombination(STANDARD_METHOD_COMBINATION)
    return comb


def call_generic_function(gf: GenericFunction, args: List[Any]) -> Any:
    """Call a generic function: compute the applicable methods, then let the
    generic function's method combination assemble and run them (CLHS
    7.6.6)."""
    if not gf.methods:
        installer = _default_method_installers.get(_gf_name(gf))
        if installer is not None:
            installer(gf)

    applicable = compute_applicable_methods(gf, args)
    if not applicable:
        # CLHS 7.6.6: no applicable methods is decided *before* the method
        # combination is consulted, and is an error for every combination --
        # not something a combination can answer by combining nothing. A
        # long-form combination whose body maps over an empty method group
        # otherwise happily produces `(vector)` and returns #().
        _no_applicable_method(gf, args)
    return method_combination_of(gf).invoke(gf, applicable, args)


_UNSET_KEYWORD_CONTEXT = object()


def _compute_frame_keyword_context(frame: Dict[str, Any]) -> Optional[Any]:
    """The CLHS 7.6.5 keyword-argument validity in force for one method
    invocation: the union of the keyword parameters named by the generic
    function's lambda list and by the lambda list of every *applicable*
    method, plus whether &allow-other-keys applies anywhere (in the generic
    function's own lambda list or in any applicable method's -- either one
    makes every keyword acceptable).

    Computed once per invocation and memoized on the frame. None means
    nothing is known (no generic function, or no Lisp lambda lists) and the
    caller's own lambda list decides alone.
    """
    gf = frame.get('gf')
    if not isinstance(gf, GenericFunction):
        return None
    from fclpy.lispfunc.evaluation_special_forms import (_keyword_param_parts,
                                                         keyword_argument_key)
    from fclpy.lispfunc.evaluation_core import parse_lambda_list

    valid: set = set()
    allow_all = False

    def absorb(lambda_list: Any) -> None:
        nonlocal allow_all
        if lambda_list is None:
            return
        try:
            tail = parse_lambda_list(lambda_list)
        except Exception:
            return
        if tail.get('allow_other_keys'):
            allow_all = True
        for spec in tail.get('keyword', []):
            try:
                keyword, _var, _default, _supplied = _keyword_param_parts(spec)
                valid.add(keyword_argument_key(keyword))
            except Exception:
                continue

    absorb(gf.lambda_list)
    try:
        applicable = compute_applicable_methods(gf, list(frame.get('args') or []))
    except Exception:
        applicable = []
    for method in applicable:
        if method is frame.get('method'):
            # The executing method's own lambda list is what the caller is
            # already checking against.
            continue
        absorb(getattr(method, 'lambda_list', None))
    return (valid, allow_all)


def call_frame_keyword_context() -> Optional[Any]:
    """The keyword-argument validity for the method currently executing on
    this thread, or None outside any method invocation. See
    `_compute_frame_keyword_context`."""
    if not _call_stack:
        return None
    frame = _call_stack[-1]
    ctx = frame.get('kw_ctx', _UNSET_KEYWORD_CONTEXT)
    if ctx is _UNSET_KEYWORD_CONTEXT:
        ctx = _compute_frame_keyword_context(frame)
        frame['kw_ctx'] = ctx
    return ctx


def current_call_frame() -> Optional[Dict[str, Any]]:
    """The frame of the method currently executing on this thread, or None
    outside any method invocation -- the thing `#'call-next-method` and
    `#'next-method-p` close over for their indefinite extent."""
    return _call_stack[-1] if _call_stack else None


def call_next_method(*args) -> Any:
    """CALL-NEXT-METHOD: call the next method in the chain the currently
    executing method was given by CALL-METHOD."""
    if not _call_stack:
        raise LispProgramError(
            "CALL-NEXT-METHOD: no method is currently executing")
    return call_next_method_in_frame(_call_stack[-1], *args)


def call_next_method_in_frame(frame: Dict[str, Any], *args) -> Any:
    """CALL-NEXT-METHOD against one captured frame -- the core the bare
    operator and the frame-capturing closures a method's environment binds
    both share, so a funcalled `#'call-next-method` after its method
    returned walks the chain it captured, not whatever is running now."""
    call_args = list(args) if args else frame['args']
    remaining = frame['next']
    if args:
        _check_cnm_argument_order(frame, call_args)
    if not remaining:
        raise LispProgramError(
            f"CALL-NEXT-METHOD: no next method for {_gf_name(frame['gf'])}")
    return call_method(remaining[0], remaining[1:], call_args)


def _check_cnm_argument_order(frame: Dict[str, Any], new_args: List[Any]) -> None:
    """CLHS call-next-method's argument rule: "the ordered set of applicable
    methods for a changed set of arguments for call-next-method must be the
    same as the ordered set of applicable methods for the original arguments
    to the generic function" -- otherwise an error is signaled. The eql-0
    method calling `(call-next-method 1)` changed which methods apply
    (its own specializer no longer matches), which is exactly the
    inconsistency the rule exists to catch."""
    gf = frame.get('gf')
    if not isinstance(gf, GenericFunction):
        return
    try:
        original = compute_applicable_methods(gf, list(frame['args']))
        changed = compute_applicable_methods(gf, list(new_args))
    except Exception:
        return
    if [id(m) for m in original] != [id(m) for m in changed]:
        raise LispProgramError(
            "CALL-NEXT-METHOD: the changed arguments do not select the same "
            f"ordered set of applicable methods for {_gf_name(gf)}")


def next_method_p() -> bool:
    """NEXT-METHOD-P: would CALL-NEXT-METHOD succeed right now?"""
    if not _call_stack:
        return False
    return bool(_call_stack[-1]['next'])


def effective_method_arguments() -> List[Any]:
    """The arguments of the generic-function call whose effective method
    form is being evaluated -- CALL-METHOD's implicit operands."""
    if not _effective_context:
        raise LispProgramError(
            "CALL-METHOD is only valid inside an effective method form")
    return _effective_context[-1]['args']


def make_method_from_thunk(run: Callable, generic_function=None) -> MakeMethod:
    """Wrap `run(*args)` as the method `(MAKE-METHOD form)` denotes, with the
    effective-method context established around it so a CALL-METHOD nested
    inside that form still knows the original call's arguments."""
    def invoke(*call_args):
        _effective_context.append(
            {'gf': generic_function, 'args': list(call_args), 'env': None})
        try:
            return run(*call_args)
        finally:
            _effective_context.pop()

    return MakeMethod(invoke, generic_function)


_builtin_classes_initialized = False

# Wrap find_class to ensure built-in classes are initialized
_original_find_class = find_class

def find_class(name: str) -> Optional[LispClass]:
    """Find a class by name, initializing built-in classes if needed."""
    global _builtin_classes_initialized
    if not _builtin_classes_initialized:
        _init_builtin_classes()
    return _original_find_class(name)


# =============================================================================
# Built-in type classes
# =============================================================================
# Every standardized class (CLHS 4.2, figure 4-8), each with the direct
# superclasses its dictionary entry specifies. This used to register every
# built-in class as a *direct subclass of T* -- no hierarchy at all -- which
# left method specificity with nothing to order specializers by (INTEGER
# versus NUMBER was a tie broken by definition order) and made every *-CPL
# test in types-and-classes/class-precedence-lists.lsp unpassable.

# name -> (direct superclass names, metaclass name). The metaobject classes
# and the classes CLHS describes as instances of standard-class keep that
# metaclass; every other built-in is a BUILT-IN-CLASS instance, which is
# what `(class-of (find-class 'symbol))` must answer.
_BUILTIN_CLASS_TABLE = {
    # -- roots --
    'T': ([], 'BUILT-IN-CLASS'),
    # -- numeric tower (CLHS 12.1) --
    'NUMBER': (['T'], 'BUILT-IN-CLASS'),
    'REAL': (['NUMBER'], 'BUILT-IN-CLASS'),
    'RATIONAL': (['REAL'], 'BUILT-IN-CLASS'),
    'INTEGER': (['RATIONAL'], 'BUILT-IN-CLASS'),
    'RATIO': (['RATIONAL'], 'BUILT-IN-CLASS'),
    'FLOAT': (['REAL'], 'BUILT-IN-CLASS'),
    'SHORT-FLOAT': (['FLOAT'], 'BUILT-IN-CLASS'),
    'SINGLE-FLOAT': (['FLOAT'], 'BUILT-IN-CLASS'),
    'DOUBLE-FLOAT': (['FLOAT'], 'BUILT-IN-CLASS'),
    'LONG-FLOAT': (['FLOAT'], 'BUILT-IN-CLASS'),
    'COMPLEX': (['NUMBER'], 'BUILT-IN-CLASS'),
    # -- symbols and lists (CLHS 4.2.1: NULL is a subclass of both SYMBOL
    #    and LIST) --
    'SYMBOL': (['T'], 'BUILT-IN-CLASS'),
    'KEYWORD': (['SYMBOL'], 'BUILT-IN-CLASS'),
    'NULL': (['SYMBOL', 'LIST'], 'BUILT-IN-CLASS'),
    'NIL': (['T'], 'BUILT-IN-CLASS'),
    'ATOM': (['T'], 'BUILT-IN-CLASS'),
    # -- sequences and arrays --
    'SEQUENCE': (['T'], 'BUILT-IN-CLASS'),
    'LIST': (['SEQUENCE'], 'BUILT-IN-CLASS'),
    'CONS': (['LIST'], 'BUILT-IN-CLASS'),
    'ARRAY': (['T'], 'BUILT-IN-CLASS'),
    'VECTOR': (['ARRAY', 'SEQUENCE'], 'BUILT-IN-CLASS'),
    'STRING': (['VECTOR'], 'BUILT-IN-CLASS'),
    'BIT-VECTOR': (['VECTOR'], 'BUILT-IN-CLASS'),
    'SIMPLE-ARRAY': (['ARRAY'], 'BUILT-IN-CLASS'),
    'SIMPLE-VECTOR': (['SIMPLE-ARRAY', 'VECTOR'], 'BUILT-IN-CLASS'),
    'SIMPLE-STRING': (['SIMPLE-ARRAY', 'STRING'], 'BUILT-IN-CLASS'),
    'SIMPLE-BIT-VECTOR': (['SIMPLE-ARRAY', 'BIT-VECTOR'], 'BUILT-IN-CLASS'),
    # -- characters --
    'CHARACTER': (['T'], 'BUILT-IN-CLASS'),
    'BASE-CHAR': (['CHARACTER'], 'BUILT-IN-CLASS'),
    'STANDARD-CHAR': (['CHARACTER'], 'BUILT-IN-CLASS'),
    'EXTENDED-CHAR': (['CHARACTER'], 'BUILT-IN-CLASS'),
    # -- functions and the metaobject family --
    'FUNCTION': (['T'], 'BUILT-IN-CLASS'),
    'COMPILED-FUNCTION': (['FUNCTION'], 'BUILT-IN-CLASS'),
    # CLHS 4.2.2 permits (and the metaclass test below requires) the
    # metaobject classes to be standard-objects.
    'GENERIC-FUNCTION': (['FUNCTION', 'STANDARD-OBJECT'], 'STANDARD-CLASS'),
    'STANDARD-GENERIC-FUNCTION': (['GENERIC-FUNCTION'], 'STANDARD-CLASS'),
    'METHOD': (['STANDARD-OBJECT'], 'STANDARD-CLASS'),
    'STANDARD-METHOD': (['METHOD'], 'STANDARD-CLASS'),
    'METHOD-COMBINATION': (['STANDARD-OBJECT'], 'STANDARD-CLASS'),
    'CLASS': (['STANDARD-OBJECT'], 'STANDARD-CLASS'),
    'STANDARD-CLASS': (['CLASS'], 'STANDARD-CLASS'),
    'BUILT-IN-CLASS': (['CLASS'], 'STANDARD-CLASS'),
    'STRUCTURE-CLASS': (['CLASS'], 'STANDARD-CLASS'),
    'STANDARD-OBJECT': (['T'], 'STANDARD-CLASS'),
    'STRUCTURE-OBJECT': (['T'], 'STRUCTURE-CLASS'),
    # -- other system classes --
    'HASH-TABLE': (['T'], 'BUILT-IN-CLASS'),
    'PACKAGE': (['T'], 'BUILT-IN-CLASS'),
    'PATHNAME': (['T'], 'BUILT-IN-CLASS'),
    'LOGICAL-PATHNAME': (['PATHNAME'], 'BUILT-IN-CLASS'),
    'READTABLE': (['T'], 'BUILT-IN-CLASS'),
    'RANDOM-STATE': (['T'], 'BUILT-IN-CLASS'),
    'RESTART': (['T'], 'BUILT-IN-CLASS'),
    'STREAM': (['T'], 'BUILT-IN-CLASS'),
    'BROADCAST-STREAM': (['STREAM'], 'BUILT-IN-CLASS'),
    'CONCATENATED-STREAM': (['STREAM'], 'BUILT-IN-CLASS'),
    'ECHO-STREAM': (['STREAM'], 'BUILT-IN-CLASS'),
    'FILE-STREAM': (['STREAM'], 'BUILT-IN-CLASS'),
    'STRING-STREAM': (['STREAM'], 'BUILT-IN-CLASS'),
    'SYNONYM-STREAM': (['STREAM'], 'BUILT-IN-CLASS'),
    'TWO-WAY-STREAM': (['STREAM'], 'BUILT-IN-CLASS'),
    # -- conditions (CLHS 9.1.2.1's own superclass lists) --
    'CONDITION': (['T'], 'STANDARD-CLASS'),
    'SERIOUS-CONDITION': (['CONDITION'], 'STANDARD-CLASS'),
    'WARNING': (['CONDITION'], 'STANDARD-CLASS'),
    'STYLE-WARNING': (['WARNING'], 'STANDARD-CLASS'),
    'STORAGE-CONDITION': (['SERIOUS-CONDITION'], 'STANDARD-CLASS'),
    'ERROR': (['SERIOUS-CONDITION'], 'STANDARD-CLASS'),
    'SIMPLE-CONDITION': (['CONDITION'], 'STANDARD-CLASS'),
    'SIMPLE-ERROR': (['SIMPLE-CONDITION', 'ERROR'], 'STANDARD-CLASS'),
    'SIMPLE-WARNING': (['SIMPLE-CONDITION', 'WARNING'], 'STANDARD-CLASS'),
    'SIMPLE-TYPE-ERROR': (['SIMPLE-CONDITION', 'TYPE-ERROR'], 'STANDARD-CLASS'),
    'TYPE-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'PARSE-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'PROGRAM-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'CONTROL-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'CELL-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'UNBOUND-VARIABLE': (['CELL-ERROR'], 'STANDARD-CLASS'),
    'UNDEFINED-VARIABLE': (['CELL-ERROR'], 'STANDARD-CLASS'),
    'UNDEFINED-FUNCTION': (['CELL-ERROR'], 'STANDARD-CLASS'),
    'UNBOUND-SLOT': (['CELL-ERROR'], 'STANDARD-CLASS'),
    'ARITHMETIC-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'DIVISION-BY-ZERO': (['ARITHMETIC-ERROR'], 'STANDARD-CLASS'),
    'FLOATING-POINT-INEXACT': (['ARITHMETIC-ERROR'], 'STANDARD-CLASS'),
    'FLOATING-POINT-INVALID-OPERATION': (['ARITHMETIC-ERROR'], 'STANDARD-CLASS'),
    'FLOATING-POINT-OVERFLOW': (['ARITHMETIC-ERROR'], 'STANDARD-CLASS'),
    'FLOATING-POINT-UNDERFLOW': (['ARITHMETIC-ERROR'], 'STANDARD-CLASS'),
    'STREAM-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'END-OF-FILE': (['STREAM-ERROR'], 'STANDARD-CLASS'),
    'FILE-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'PACKAGE-ERROR': (['ERROR'], 'STANDARD-CLASS'),
    'PRINT-NOT-READABLE': (['ERROR'], 'STANDARD-CLASS'),
    'READER-ERROR': (['PARSE-ERROR', 'STREAM-ERROR'], 'STANDARD-CLASS'),
}

# The condition classes in most-specific-first order. `class_of` walks this
# list with isinstance to answer the most specific modeled condition class of
# a condition object (conditions are plain Python classes, not LispInstances).
_CONDITION_NAMES_MOST_SPECIFIC_FIRST = (
    'END-OF-FILE',
    'READER-ERROR',
    'FLOATING-POINT-INEXACT',
    'FLOATING-POINT-INVALID-OPERATION',
    'FLOATING-POINT-OVERFLOW',
    'FLOATING-POINT-UNDERFLOW',
    'DIVISION-BY-ZERO',
    'UNBOUND-SLOT',
    'UNBOUND-VARIABLE',
    'UNDEFINED-VARIABLE',
    'UNDEFINED-FUNCTION',
    'SIMPLE-TYPE-ERROR',
    'SIMPLE-ERROR',
    'SIMPLE-WARNING',
    'STYLE-WARNING',
    'TYPE-ERROR',
    'PARSE-ERROR',
    'PROGRAM-ERROR',
    'CONTROL-ERROR',
    'CELL-ERROR',
    'ARITHMETIC-ERROR',
    'STREAM-ERROR',
    'FILE-ERROR',
    'PACKAGE-ERROR',
    'PRINT-NOT-READABLE',
    'STORAGE-CONDITION',
    'SIMPLE-CONDITION',
    'WARNING',
    'ERROR',
    'SERIOUS-CONDITION',
    'CONDITION',
)


def _init_builtin_classes():
    """Register the standardized classes of CLHS 4.2 with the superclass
    edges their dictionary entries give them."""
    global _builtin_classes_initialized
    if _builtin_classes_initialized:
        return
    _builtin_classes_initialized = True

    from fclpy.lisptype import COMMON_LISP_PACKAGE

    classes = {}
    for type_name, (_supers, _metaclass) in _BUILTIN_CLASS_TABLE.items():
        sym = COMMON_LISP_PACKAGE.intern_symbol(type_name)
        classes[type_name] = LispClass(name=sym, direct_superclasses=[],
                                       direct_slots=[],
                                       metaclass_name=_metaclass)
    # Wire the superclass edges in a second pass, now that every object
    # exists (the table is not topologically ordered).
    for type_name, (supers, _metaclass) in _BUILTIN_CLASS_TABLE.items():
        classes[type_name].direct_superclasses = [classes[s] for s in supers]
    for cls in classes.values():
        register_class(cls)


# Initialize built-in classes when module is loaded
_init_builtin_classes()
