"""Miscellaneous utility functions and system operations.

This module re-exports from submodules organized by functional area:
- utilities_system: System information, time, environment, random
- utilities_symbols: Symbol and package management
- utilities_functions: Function binding, definition, macros
- utilities_errors: Error handling, conditions, restarts, warnings
- utilities_misc: Hash tables, arrays, CLOS, WITH- macros, stubs
"""

from .utilities_system import *
from .utilities_symbols import *
from .utilities_functions import *
from .utilities_errors import *
from .utilities_misc import *

__all__ = [
    # System and environment (utilities_system)
    'get_universal_time',
    'decode_universal_time',
    'get_decoded_time',
    'sleep',
    'lisp_implementation_type',
    'lisp_implementation_version',
    'machine_instance',
    'machine_type',
    'machine_version',
    'software_type',
    'software_version',
    'short_site_name',
    'long_site_name',
    'user_homedir_pathname',
    'get_env',
    'exit',
    'quit',
    'random',
    'make_random_state',
    'random_state_p',
    
    # Symbols and packages (utilities_symbols)
    'symbol_name',
    'symbol_package',
    'symbol_value',
    'make_symbol',
    'copy_symbol',
    'gensym',
    'in_package',
    'import_symbol',
    'intern',
    'find_symbol',
    'find_package',
    'find_all_symbols',
    'export',
    'gentemp',
    'apropos',
    'apropos_list',
    
    # Functions and macros (utilities_functions)
    'fboundp',
    'fmakunbound',
    'fdefinition',
    'symbol_function',
    'functionp',
    'compiled_function_p',
    'compile_fn',
    'macro_function',
    'compiler_macro_function',
    'macrolet',
    'symbol_macrolet',
    'define_compiler_macro',
    'function_keywords',
    'function_lambda_expression',
    'special_operator_p',
    'eval_when',
    'locally',
    'eval_progv',
    'dynamic_extent',
    'ftype',
    'notinline',
    'inline',
    'lambda_list_keywords',
    'lambda_parameters_limit',
    'coerce',  # Type coercion function
    
    # Error handling (utilities_errors)
    'define_condition',
    'make_condition',
    'signal_fn',
    'error_fn',
    'warn_fn',
    'muffle_warning',
    'compute_restarts',
    'find_restart',
    'invoke_restart',
    'invoke_restart_interactively',
    'restart_name',
    'abort',
    'continue_fn',
    'invoke_debugger',
    'store_value',
    'use_value',
    'with_simple_restart_macro',
    'check_type_macro',
    'method_combination_error',
    'invalid_method_error',
    'package_error_package',
    'type_error_datum',
    'type_error_expected_type',
    
    # Hash tables, arrays, CLOS, WITH macros, misc (utilities_misc)
    'make_hash_table',
    'gethash',
    'remhash',
    'maphash',
    'clrhash',
    'sxhash',
    'hash_table_count',
    'hash_table_size',
    'hash_table_test',
    'hash_table_rehash_size',
    'hash_table_rehash_threshold',
    'array_row_major_index',
    'upgraded_array_element_type',
    'upgraded_complex_part_type',
    'adjustable_array_p',
    'row_major_aref',
    'find_class',
    'make_instance',
    'allocate_instance',
    'initialize_instance',
    'reinitialize_instance',
    'shared_initialize',
    'update_instance_for_different_class',
    'update_instance_for_redefined_class',
    'class_of',
    'class_name',
    'change_class',
    'built_in_class',
    'standard_class',
    'standard_object',
    'structure_class',
    'structure_object',
    'slot_boundp',
    'slot_exists_p',
    'slot_makunbound',
    'slot_unbound',
    'slot_value',
    'set_slot_value',
    'slot_missing',
    'find_method',
    'remove_method',
    'defmethod',
    'make_method',
    'method_function',
    'method_generic_function',
    'method_specializers',
    'method_lambda_list',
    'method_qualifiers',
    'next_method_p',
    'no_applicable_method',
    'no_next_method',
    'call_method',
    'call_next_method',
    'compute_applicable_methods',
    'ensure_generic_function',
    'generic_function_lambda_list',
    'generic_function_methods',
    'generic_function_name',
    'with_pprint_logical_block',
    'complex_fn',
    'load_time_value',
    'load',
    'load_logical_pathname_translations',
    'logical_pathname_translations',
    'directory',
    'ensure_directories_exist',
    'proclaim',
    'describe',
    'inspect_object',
    'type_fn',
    'copy_tree',
    # 'incf' removed - now a special form
    'octets_to_string',
    'string_to_octets',
    'get',
    'rplaca',
    'rplacd',
    'char_bits_limit',
    'char_font_limit',
    'optimize',
    'special',
    'nil_symbol',
    'nil_symbol_function',
    't_symbol',
    't_symbol_function',
    'keyword_type',
    'integer_type',
    'fixnum_type',
    'double_float_type',
    'single_float_type',
    'short_float_type',
    'extended_char_type',
    'hash_table_type',
    'generic_function_type',
    'file_stream_type',
    'file_error_type',
    'end_of_file_type',
    'floating_point_inexact_type',
    'floating_point_invalid_operation_type',
    'floating_point_overflow_type',
    'floating_point_underflow_type',
    'arithmetic_error_operands',
    'arithmetic_error_operation',
    'file_error_pathname',
    'multiple_value_bind',
    'multiple_value_call',
    'make_package',
    'package_name',
    'package_nicknames',
    'rename_package',
    'package_use_list',
    'package_used_by_list',
    'package_shadowing_symbols',
    'list_all_packages',
    'unintern',
    'unexport',
    'delete_package',
    'shadowing_import',
    'shadow',
    'use_package',
    'unuse_package',
    'macroexpand',
    'macroexpand_1',
    'array_dimension_limit',
    'array_rank_limit',
    'array_total_size_limit',
    'call_arguments_limit',
    'multiple_values_limit',
    'char_code_limit',
    # do_symbols, do_external_symbols, do_all_symbols are now special forms
    'with_package_iterator',
    'declaim',
    'declare',
    'defclass',
    'defconstant',
    'defgeneric',
    'defpackage',
    'deftype',
    'defparameter',
    'echo_stream_p',
    'broadcast_stream_p',
    'concatenated_stream_p',
    'file_stream_p',
    'string_stream_p',
    'synonym_stream_p',
    'two_way_stream_p',
    'break_fn',
    'continue_fn',
    'ed',
    'dribble',
    'disassemble',
    'room',
    'step',
    'trace',
    'untrace',
    'provide',
    'require',
    'make_load_form',
    'make_load_form_saving_slots',
    'fill_pointer',
    'documentation',
    'get_optimization_policy',
    'is_variable_special',
]

