"""Hash tables, arrays, CLOS operations, WITH macros, and miscellaneous utilities.

This module re-exports all functions from the split modules:
- misc_hashtables: Hash table and array operations
- misc_clos: CLOS class/instance/slot/method operations
- misc_packages: Package operations and macro expansion
- misc_macros: WITH macros, type designators, system limits, debugging
"""

# Re-export everything from split modules
from .misc_hashtables import (
    LispHashTable,
    is_hash_table,
    make_hash_table,
    hash_table_p,
    gethash,
    puthash,
    remhash,
    maphash,
    clrhash,
    sxhash,
    hash_table_count,
    hash_table_size,
    hash_table_test,
    hash_table_rehash_size,
    hash_table_rehash_threshold,
    upgraded_complex_part_type,
)

from .misc_clos import (
    find_class,
    allocate_instance,
    initialize_instance,
    reinitialize_instance,
    shared_initialize,
    update_instance_for_different_class,
    update_instance_for_redefined_class,
    class_of,
    change_class,
    built_in_class,
    standard_class,
    standard_object,
    structure_class,
    structure_object,
    slot_boundp,
    slot_exists_p,
    slot_makunbound,
    slot_unbound,
    slot_value,
    set_slot_value,
    slot_missing,
    find_method,
    remove_method,
    make_method,
    method_function,
    method_generic_function,
    method_specializers,
    method_lambda_list,
    method_qualifiers,
    next_method_p,
    no_applicable_method,
    no_next_method,
    call_method,
    call_next_method,
    compute_applicable_methods,
    ensure_generic_function,
    generic_function_lambda_list,
    generic_function_methods,
    generic_function_name,
    make_load_form,
)

# MAKE-INSTANCE's one implementation lives in `classes.py` -- the
# registration there binds the MAKE-INSTANCE GenericFunction itself into
# every function cell (CLHS 7.1), and this module only re-exports the
# Python-level callable for `from .utilities import *` consumers. The
# second, initarg-dropping copy this used to import from `misc_clos` is
# deleted (standing rule 3).
from .classes import make_instance

from .misc_packages import (
    make_package,
    package_name,
    package_nicknames,
    rename_package,
    package_use_list,
    package_used_by_list,
    package_shadowing_symbols,
    list_all_packages,
    unintern,
    unexport,
    delete_package,
    shadowing_import,
    shadow,
    use_package,
    unuse_package,
    macroexpand,
    macroexpand_1,
)

from .classes import defclass
from .misc_clos import class_name

from .arrays import (
    fill_pointer,
    array_row_major_index,
    upgraded_array_element_type,
    adjustable_array_p,
    row_major_aref,
)

from .pathnames import (
    load_logical_pathname_translations,
    logical_pathname_translations,
    directory,
    ensure_directories_exist,
)

from .standard_macros import (
    _declaim_expander as declaim,
    _step_expander as step,
)

from .misc_macros import (
    declare,
    with_pprint_logical_block,
    complex_fn,
    load_time_value,
    load,
    proclaim,
    describe,
    inspect_object,
    type_fn,
    copy_tree,
    # Note: incf removed - now a special form in evaluation_special_forms.py
    octets_to_string,
    string_to_octets,
    get,
    rplaca,
    rplacd,
    char_bits_limit,
    char_font_limit,
    optimize,
    special,
    nil_symbol,
    nil_symbol_function,
    t_symbol,
    t_symbol_function,
    keyword_type,
    integer_type,
    fixnum_type,
    double_float_type,
    single_float_type,
    short_float_type,
    extended_char_type,
    hash_table_type,
    generic_function_type,
    file_stream_type,
    file_error_type,
    end_of_file_type,
    floating_point_inexact_type,
    floating_point_invalid_operation_type,
    floating_point_overflow_type,
    floating_point_underflow_type,
    arithmetic_error_operands,
    arithmetic_error_operation,
    file_error_pathname,
    multiple_value_bind,
    multiple_value_call,
    array_dimension_limit,
    array_rank_limit,
    array_total_size_limit,
    call_arguments_limit,
    multiple_values_limit,
    char_code_limit,
    # do_symbols, do_external_symbols, do_all_symbols are now special forms
    # with_package_iterator is now a macro in evaluation_special_forms.py
    # declaim and step are now macros in standard_macros.py (imported above)
    declare,
    defgeneric,
    defpackage,
    deftype,
    defparameter,
    echo_stream_p,
    broadcast_stream_p,
    concatenated_stream_p,
    file_stream_p,
    string_stream_p,
    synonym_stream_p,
    two_way_stream_p,
    break_fn,
    ed,
    dribble,
    disassemble,
    room,
    provide,
    require,
    make_load_form_saving_slots,
    get_optimization_policy,
    is_variable_special,
)

# DOCUMENTATION is a standard generic function (CLHS 25.1.3); its default
# methods live in misc_clos.py's `_PROTOCOL_DEFAULTS`. Re-exported here so
# the module's flat namespace keeps answering for it.
from .misc_clos import _default_documentation as documentation


__all__ = [
    'LispHashTable',
    'is_hash_table',
    'make_hash_table',
    'hash_table_p',
    'gethash',
    'puthash',
    'remhash',
    'maphash',
    'clrhash',
    'sxhash',
    'hash_table_count',
    'hash_table_size',
    'hash_table_test',
    'hash_table_rehash_size',
    'hash_table_rehash_threshold',
    'array_row_major_index',
    'upgraded_array_element_type',
    'upgraded_complex_part_type',
    'adjustable_array_p',
    'row_major_aref',
    'find_class',
    'make_instance',
    'allocate_instance',
    'initialize_instance',
    'reinitialize_instance',
    'shared_initialize',
    'update_instance_for_different_class',
    'update_instance_for_redefined_class',
    'class_of',
    'class_name',
    'change_class',
    'built_in_class',
    'standard_class',
    'standard_object',
    'structure_class',
    'structure_object',
    'slot_boundp',
    'slot_exists_p',
    'slot_makunbound',
    'slot_unbound',
    'slot_value',
    'set_slot_value',
    'slot_missing',
    'find_method',
    'remove_method',
    'make_method',
    'method_function',
    'method_generic_function',
    'method_specializers',
    'method_lambda_list',
    'method_qualifiers',
    'next_method_p',
    'no_applicable_method',
    'no_next_method',
    'call_method',
    'call_next_method',
    'compute_applicable_methods',
    'ensure_generic_function',
    'generic_function_lambda_list',
    'generic_function_methods',
    'generic_function_name',
    'with_pprint_logical_block',
    'complex_fn',
    'load_time_value',
    'load',
    'load_logical_pathname_translations',
    'logical_pathname_translations',
    'directory',
    'ensure_directories_exist',
    'proclaim',
    'describe',
    'inspect_object',
    'type_fn',
    'copy_tree',
    # 'incf' removed - now a special form
    'octets_to_string',
    'string_to_octets',
    'get',
    'rplaca',
    'rplacd',
    'char_bits_limit',
    'char_font_limit',
    'optimize',
    'special',
    'nil_symbol',
    'nil_symbol_function',
    't_symbol',
    't_symbol_function',
    'keyword_type',
    'integer_type',
    'fixnum_type',
    'double_float_type',
    'single_float_type',
    'short_float_type',
    'extended_char_type',
    'hash_table_type',
    'generic_function_type',
    'file_stream_type',
    'file_error_type',
    'end_of_file_type',
    'floating_point_inexact_type',
    'floating_point_invalid_operation_type',
    'floating_point_overflow_type',
    'floating_point_underflow_type',
    'arithmetic_error_operands',
    'arithmetic_error_operation',
    'file_error_pathname',
    'multiple_value_bind',
    'multiple_value_call',
    'make_package',
    'package_name',
    'package_nicknames',
    'rename_package',
    'package_use_list',
    'package_used_by_list',
    'package_shadowing_symbols',
    'list_all_packages',
    'unintern',
    'unexport',
    'shadowing_import',
    'shadow',
    'use_package',
    'unuse_package',
    'macroexpand',
    'macroexpand_1',
    'array_dimension_limit',
    'array_rank_limit',
    'array_total_size_limit',
    'call_arguments_limit',
    'multiple_values_limit',
    'char_code_limit',
    # do_symbols, do_external_symbols, do_all_symbols are now special forms
    # with_package_iterator is now a macro in evaluation_special_forms.py
    'declaim',
    'declare',
    'defclass',
    'defgeneric',
    'defpackage',
    'deftype',
    'defparameter',
    'echo_stream_p',
    'broadcast_stream_p',
    'concatenated_stream_p',
    'file_stream_p',
    'string_stream_p',
    'synonym_stream_p',
    'two_way_stream_p',
    'break_fn',
    'ed',
    'dribble',
    'disassemble',
    'room',
    'step',
    'provide',
    'require',
    # 'make_load_form' is now a generic function registered in misc_clos.py
    'make_load_form_saving_slots',
    'fill_pointer',
    'documentation',
    'get_optimization_policy',
    'is_variable_special',
    'delete_package'
]
